// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/vault/api"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthTokenAPI is an autogenerated mock type for the AuthTokenAPI type
type MockAuthTokenAPI struct {
	mock.Mock
}

type MockAuthTokenAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenAPI) EXPECT() *MockAuthTokenAPI_Expecter {
	return &MockAuthTokenAPI_Expecter{mock: &_m.Mock}
}

// RenewSelfWithContext provides a mock function with given fields: ctx, increment
func (_m *MockAuthTokenAPI) RenewSelfWithContext(ctx context.Context, increment int) (*api.Secret, error) {
	ret := _m.Called(ctx, increment)

	if len(ret) == 0 {
		panic("no return value specified for RenewSelfWithContext")
	}

	var r0 *api.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*api.Secret, error)); ok {
		return rf(ctx, increment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *api.Secret); ok {
		r0 = rf(ctx, increment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, increment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthTokenAPI_RenewSelfWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewSelfWithContext'
type MockAuthTokenAPI_RenewSelfWithContext_Call struct {
	*mock.Call
}

// RenewSelfWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - increment int
func (_e *MockAuthTokenAPI_Expecter) RenewSelfWithContext(ctx interface{}, increment interface{}) *MockAuthTokenAPI_RenewSelfWithContext_Call {
	return &MockAuthTokenAPI_RenewSelfWithContext_Call{Call: _e.mock.On("RenewSelfWithContext", ctx, increment)}
}

func (_c *MockAuthTokenAPI_RenewSelfWithContext_Call) Run(run func(ctx context.Context, increment int)) *MockAuthTokenAPI_RenewSelfWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAuthTokenAPI_RenewSelfWithContext_Call) Return(_a0 *api.Secret, _a1 error) *MockAuthTokenAPI_RenewSelfWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthTokenAPI_RenewSelfWithContext_Call) RunAndReturn(run func(context.Context, int) (*api.Secret, error)) *MockAuthTokenAPI_RenewSelfWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthTokenAPI creates a new instance of MockAuthTokenAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenAPI {
	mock := &MockAuthTokenAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
