// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/vault/api"

	mock "github.com/stretchr/testify/mock"
)

// MockLogicalAPI is an autogenerated mock type for the LogicalAPI type
type MockLogicalAPI struct {
	mock.Mock
}

type MockLogicalAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogicalAPI) EXPECT() *MockLogicalAPI_Expecter {
	return &MockLogicalAPI_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: path, data
func (_m *MockLogicalAPI) Write(path string, data map[string]any) (*api.Secret, error) {
	ret := _m.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 *api.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]any) (*api.Secret, error)); ok {
		return rf(path, data)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]any) *api.Secret); ok {
		r0 = rf(path, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(string, map[string]any) error); ok {
		r1 = rf(path, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogicalAPI_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockLogicalAPI_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - path string
//   - data map[string]any
func (_e *MockLogicalAPI_Expecter) Write(path interface{}, data interface{}) *MockLogicalAPI_Write_Call {
	return &MockLogicalAPI_Write_Call{Call: _e.mock.On("Write", path, data)}
}

func (_c *MockLogicalAPI_Write_Call) Run(run func(path string, data map[string]any)) *MockLogicalAPI_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]any))
	})
	return _c
}

func (_c *MockLogicalAPI_Write_Call) Return(_a0 *api.Secret, _a1 error) *MockLogicalAPI_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogicalAPI_Write_Call) RunAndReturn(run func(string, map[string]any) (*api.Secret, error)) *MockLogicalAPI_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogicalAPI creates a new instance of MockLogicalAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogicalAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogicalAPI {
	mock := &MockLogicalAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
