// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockSleeper is an autogenerated mock type for the Sleeper type
type MockSleeper struct {
	mock.Mock
}

type MockSleeper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSleeper) EXPECT() *MockSleeper_Expecter {
	return &MockSleeper_Expecter{mock: &_m.Mock}
}

// After provides a mock function with given fields: d
func (_m *MockSleeper) After(d time.Duration) <-chan time.Time {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for After")
	}

	var r0 <-chan time.Time
	if rf, ok := ret.Get(0).(func(time.Duration) <-chan time.Time); ok {
		r0 = rf(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}

	return r0
}

// MockSleeper_After_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'After'
type MockSleeper_After_Call struct {
	*mock.Call
}

// After is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockSleeper_Expecter) After(d interface{}) *MockSleeper_After_Call {
	return &MockSleeper_After_Call{Call: _e.mock.On("After", d)}
}

func (_c *MockSleeper_After_Call) Run(run func(d time.Duration)) *MockSleeper_After_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockSleeper_After_Call) Return(_a0 <-chan time.Time) *MockSleeper_After_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSleeper_After_Call) RunAndReturn(run func(time.Duration) <-chan time.Time) *MockSleeper_After_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSleeper creates a new instance of MockSleeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSleeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSleeper {
	mock := &MockSleeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
