// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "github.com/Arubacloud/arubacloud-resource-operator/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// MockIVaultClient is an autogenerated mock type for the IVaultClient type
type MockIVaultClient struct {
	mock.Mock
}

type MockIVaultClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIVaultClient) EXPECT() *MockIVaultClient_Expecter {
	return &MockIVaultClient_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function with no fields
func (_m *MockIVaultClient) Auth() client.AuthAPI {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 client.AuthAPI
	if rf, ok := ret.Get(0).(func() client.AuthAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.AuthAPI)
		}
	}

	return r0
}

// MockIVaultClient_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockIVaultClient_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
func (_e *MockIVaultClient_Expecter) Auth() *MockIVaultClient_Auth_Call {
	return &MockIVaultClient_Auth_Call{Call: _e.mock.On("Auth")}
}

func (_c *MockIVaultClient_Auth_Call) Run(run func()) *MockIVaultClient_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIVaultClient_Auth_Call) Return(_a0 client.AuthAPI) *MockIVaultClient_Auth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIVaultClient_Auth_Call) RunAndReturn(run func() client.AuthAPI) *MockIVaultClient_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// KVv2 provides a mock function with given fields: mount
func (_m *MockIVaultClient) KVv2(mount string) client.KvAPI {
	ret := _m.Called(mount)

	if len(ret) == 0 {
		panic("no return value specified for KVv2")
	}

	var r0 client.KvAPI
	if rf, ok := ret.Get(0).(func(string) client.KvAPI); ok {
		r0 = rf(mount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.KvAPI)
		}
	}

	return r0
}

// MockIVaultClient_KVv2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KVv2'
type MockIVaultClient_KVv2_Call struct {
	*mock.Call
}

// KVv2 is a helper method to define mock.On call
//   - mount string
func (_e *MockIVaultClient_Expecter) KVv2(mount interface{}) *MockIVaultClient_KVv2_Call {
	return &MockIVaultClient_KVv2_Call{Call: _e.mock.On("KVv2", mount)}
}

func (_c *MockIVaultClient_KVv2_Call) Run(run func(mount string)) *MockIVaultClient_KVv2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIVaultClient_KVv2_Call) Return(_a0 client.KvAPI) *MockIVaultClient_KVv2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIVaultClient_KVv2_Call) RunAndReturn(run func(string) client.KvAPI) *MockIVaultClient_KVv2_Call {
	_c.Call.Return(run)
	return _c
}

// Logical provides a mock function with no fields
func (_m *MockIVaultClient) Logical() client.LogicalAPI {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logical")
	}

	var r0 client.LogicalAPI
	if rf, ok := ret.Get(0).(func() client.LogicalAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.LogicalAPI)
		}
	}

	return r0
}

// MockIVaultClient_Logical_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logical'
type MockIVaultClient_Logical_Call struct {
	*mock.Call
}

// Logical is a helper method to define mock.On call
func (_e *MockIVaultClient_Expecter) Logical() *MockIVaultClient_Logical_Call {
	return &MockIVaultClient_Logical_Call{Call: _e.mock.On("Logical")}
}

func (_c *MockIVaultClient_Logical_Call) Run(run func()) *MockIVaultClient_Logical_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIVaultClient_Logical_Call) Return(_a0 client.LogicalAPI) *MockIVaultClient_Logical_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIVaultClient_Logical_Call) RunAndReturn(run func() client.LogicalAPI) *MockIVaultClient_Logical_Call {
	_c.Call.Return(run)
	return _c
}

// SetNamespace provides a mock function with given fields: namespace
func (_m *MockIVaultClient) SetNamespace(namespace string) {
	_m.Called(namespace)
}

// MockIVaultClient_SetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNamespace'
type MockIVaultClient_SetNamespace_Call struct {
	*mock.Call
}

// SetNamespace is a helper method to define mock.On call
//   - namespace string
func (_e *MockIVaultClient_Expecter) SetNamespace(namespace interface{}) *MockIVaultClient_SetNamespace_Call {
	return &MockIVaultClient_SetNamespace_Call{Call: _e.mock.On("SetNamespace", namespace)}
}

func (_c *MockIVaultClient_SetNamespace_Call) Run(run func(namespace string)) *MockIVaultClient_SetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIVaultClient_SetNamespace_Call) Return() *MockIVaultClient_SetNamespace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIVaultClient_SetNamespace_Call) RunAndReturn(run func(string)) *MockIVaultClient_SetNamespace_Call {
	_c.Run(run)
	return _c
}

// SetToken provides a mock function with given fields: token
func (_m *MockIVaultClient) SetToken(token string) {
	_m.Called(token)
}

// MockIVaultClient_SetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToken'
type MockIVaultClient_SetToken_Call struct {
	*mock.Call
}

// SetToken is a helper method to define mock.On call
//   - token string
func (_e *MockIVaultClient_Expecter) SetToken(token interface{}) *MockIVaultClient_SetToken_Call {
	return &MockIVaultClient_SetToken_Call{Call: _e.mock.On("SetToken", token)}
}

func (_c *MockIVaultClient_SetToken_Call) Run(run func(token string)) *MockIVaultClient_SetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIVaultClient_SetToken_Call) Return() *MockIVaultClient_SetToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIVaultClient_SetToken_Call) RunAndReturn(run func(string)) *MockIVaultClient_SetToken_Call {
	_c.Run(run)
	return _c
}

// NewMockIVaultClient creates a new instance of MockIVaultClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIVaultClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIVaultClient {
	mock := &MockIVaultClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
