// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gocloak "github.com/Nerzal/gocloak/v13"
	mock "github.com/stretchr/testify/mock"
)

// MockIOauthClient is an autogenerated mock type for the IOauthClient type
type MockIOauthClient struct {
	mock.Mock
}

type MockIOauthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOauthClient) EXPECT() *MockIOauthClient_Expecter {
	return &MockIOauthClient_Expecter{mock: &_m.Mock}
}

// LoginClient provides a mock function with given fields: ctx, clientID, clientSecret, realm, options
func (_m *MockIOauthClient) LoginClient(ctx context.Context, clientID string, clientSecret string, realm string, options ...string) (*gocloak.JWT, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clientID, clientSecret, realm)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LoginClient")
	}

	var r0 *gocloak.JWT
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...string) (*gocloak.JWT, error)); ok {
		return rf(ctx, clientID, clientSecret, realm, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...string) *gocloak.JWT); ok {
		r0 = rf(ctx, clientID, clientSecret, realm, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.JWT)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, ...string) error); ok {
		r1 = rf(ctx, clientID, clientSecret, realm, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOauthClient_LoginClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginClient'
type MockIOauthClient_LoginClient_Call struct {
	*mock.Call
}

// LoginClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - clientSecret string
//   - realm string
//   - options ...string
func (_e *MockIOauthClient_Expecter) LoginClient(ctx interface{}, clientID interface{}, clientSecret interface{}, realm interface{}, options ...interface{}) *MockIOauthClient_LoginClient_Call {
	return &MockIOauthClient_LoginClient_Call{Call: _e.mock.On("LoginClient",
		append([]interface{}{ctx, clientID, clientSecret, realm}, options...)...)}
}

func (_c *MockIOauthClient_LoginClient_Call) Run(run func(ctx context.Context, clientID string, clientSecret string, realm string, options ...string)) *MockIOauthClient_LoginClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIOauthClient_LoginClient_Call) Return(_a0 *gocloak.JWT, _a1 error) *MockIOauthClient_LoginClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOauthClient_LoginClient_Call) RunAndReturn(run func(context.Context, string, string, string, ...string) (*gocloak.JWT, error)) *MockIOauthClient_LoginClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOauthClient creates a new instance of MockIOauthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOauthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOauthClient {
	mock := &MockIOauthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
