// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/vault/api"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockKvAPI is an autogenerated mock type for the KvAPI type
type MockKvAPI struct {
	mock.Mock
}

type MockKvAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKvAPI) EXPECT() *MockKvAPI_Expecter {
	return &MockKvAPI_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, path
func (_m *MockKvAPI) Get(ctx context.Context, path string) (*api.KVSecret, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *api.KVSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.KVSecret, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.KVSecret); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.KVSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKvAPI_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKvAPI_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockKvAPI_Expecter) Get(ctx interface{}, path interface{}) *MockKvAPI_Get_Call {
	return &MockKvAPI_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockKvAPI_Get_Call) Run(run func(ctx context.Context, path string)) *MockKvAPI_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockKvAPI_Get_Call) Return(_a0 *api.KVSecret, _a1 error) *MockKvAPI_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKvAPI_Get_Call) RunAndReturn(run func(context.Context, string) (*api.KVSecret, error)) *MockKvAPI_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKvAPI creates a new instance of MockKvAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKvAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKvAPI {
	mock := &MockKvAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
