// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "gitlab.aruba.it/ingegneria/seca/operators/aruba-operator/internal/client"
)

// MockIOauth is an autogenerated mock type for the IOauth type
type MockIOauth struct {
	mock.Mock
}

type MockIOauth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOauth) EXPECT() *MockIOauth_Expecter {
	return &MockIOauth_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function with given fields: _a0
func (_m *MockIOauth) NewClient(_a0 string) client.IOauthClient {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 client.IOauthClient
	if rf, ok := ret.Get(0).(func(string) client.IOauthClient); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.IOauthClient)
		}
	}

	return r0
}

// MockIOauth_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockIOauth_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - _a0 string
func (_e *MockIOauth_Expecter) NewClient(_a0 interface{}) *MockIOauth_NewClient_Call {
	return &MockIOauth_NewClient_Call{Call: _e.mock.On("NewClient", _a0)}
}

func (_c *MockIOauth_NewClient_Call) Run(run func(_a0 string)) *MockIOauth_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOauth_NewClient_Call) Return(_a0 client.IOauthClient) *MockIOauth_NewClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOauth_NewClient_Call) RunAndReturn(run func(string) client.IOauthClient) *MockIOauth_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOauth creates a new instance of MockIOauth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOauth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOauth {
	mock := &MockIOauth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
