// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "gitlab.aruba.it/ingegneria/seca/operators/aruba-operator/internal/client"
)

// MockAuthAPI is an autogenerated mock type for the AuthAPI type
type MockAuthAPI struct {
	mock.Mock
}

type MockAuthAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAPI) EXPECT() *MockAuthAPI_Expecter {
	return &MockAuthAPI_Expecter{mock: &_m.Mock}
}

// Token provides a mock function with no fields
func (_m *MockAuthAPI) Token() client.AuthTokenAPI {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 client.AuthTokenAPI
	if rf, ok := ret.Get(0).(func() client.AuthTokenAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.AuthTokenAPI)
		}
	}

	return r0
}

// MockAuthAPI_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockAuthAPI_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockAuthAPI_Expecter) Token() *MockAuthAPI_Token_Call {
	return &MockAuthAPI_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockAuthAPI_Token_Call) Run(run func()) *MockAuthAPI_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthAPI_Token_Call) Return(_a0 client.AuthTokenAPI) *MockAuthAPI_Token_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthAPI_Token_Call) RunAndReturn(run func() client.AuthTokenAPI) *MockAuthAPI_Token_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthAPI creates a new instance of MockAuthAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAPI {
	mock := &MockAuthAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
