# golangci-lint configuration for Arubacloud Resource Operator
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
  disable:
    - staticcheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

