filename: 'zz_generated.{{.InterfaceName}}.go'
with-expecter: true
disable-version-string: true
packages:
  github.com/Arubacloud/arubacloud-resource-operator/internal/client:
    config:
      all: true
      dir: internal/mocks
      outpkg: mocks
