filename: 'zz_generated.{{.InterfaceName}}.go'
with-expecter: true
issue-845-fix: true
resolve-type-alias: false
disable-version-string: true
packages:
  github.com/Arubacloud/arubacloud-resource-operator/internal/client:
    config:
      dir: internal/mocks/aruba
      outpkg: arubamocks
    interfaces:
      Client:
      ProjectClient:
      NetworkClient:
      VPCsClient:
      SubnetsClient:
      SecurityGroupsClient:
      SecurityGroupRulesClient:
      ElasticIPsClient:
      ComputeClient:
      CloudServersClient:
      KeyPairsClient:
      StorageClient:
      VolumesClient:
