---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arubacloud.com
  resources:
  - blockstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arubacloud.com
  resources:
  - blockstorages/finalizers
  verbs:
  - update
- apiGroups:
  - arubacloud.com
  resources:
  - blockstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arubacloud.com
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
