apiVersion: arubacloud.com/v1alpha1
kind: CloudServer
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tenant: __TENANT__
  tags:
    - aruba-operator
    - sample
  region: ITBG-Bergamo
  zone: ITBG-1
  vpcReference:
    name: __NAME__
    namespace: __NAMESPACE__
  flavorName: CSO4A8
  userData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    write_files:
      - path: /tmp/test.txt
        content: |
          This server was initialized with cloud-init.
        owner: root:root
        permissions: '0644'
  subnetReferences:
    - name: __NAME__
      namespace: __NAMESPACE__
  elasticIPReference:
    name: __NAME__
    namespace: __NAMESPACE__
  securityGroupReferences:
    - name: __NAME__
      namespace: __NAMESPACE__
  keyPairReference:
    name: __NAME__
    namespace: __NAMESPACE__
  bootVolumeReference:
    name: __NAME__
    namespace: __NAMESPACE__
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
