apiVersion: arubacloud.com/v1alpha1
kind: Subnet
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tenant: __TENANT__
  tags:
    - aruba-operator
    - sample
  region: ITBG-Bergamo
  type: Advanced
  cidr: 192.168.1.0/24
  dhcp:
    enabled: true
  vpcReference:
    name: __NAME__
    namespace: __NAMESPACE__
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
