apiVersion: arubacloud.com/v1alpha1
kind: ElasticIP
metadata:
  name: __NAME__03
  namespace: __NAMESPACE__
spec:
  tenant: __TENANT__
  tags:
    - aruba-operator
    - sample
  region: ITBG-Bergamo
  billingPeriod: Hour
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
