apiVersion: arubacloud.com/v1alpha1
kind: VPC
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tenant: __TENANT__
  tags:
    - tag-4
    - tag-3
  region: ITBG-Bergamo
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
