//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaBlockStorage) DeepCopyInto(out *ArubaBlockStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaBlockStorage.
func (in *ArubaBlockStorage) DeepCopy() *ArubaBlockStorage {
	if in == nil {
		return nil
	}
	out := new(ArubaBlockStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaBlockStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaBlockStorageList) DeepCopyInto(out *ArubaBlockStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaBlockStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaBlockStorageList.
func (in *ArubaBlockStorageList) DeepCopy() *ArubaBlockStorageList {
	if in == nil {
		return nil
	}
	out := new(ArubaBlockStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaBlockStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaBlockStorageSpec) DeepCopyInto(out *ArubaBlockStorageSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaBlockStorageSpec.
func (in *ArubaBlockStorageSpec) DeepCopy() *ArubaBlockStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaBlockStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaBlockStorageStatus) DeepCopyInto(out *ArubaBlockStorageStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaBlockStorageStatus.
func (in *ArubaBlockStorageStatus) DeepCopy() *ArubaBlockStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaBlockStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaCloudServer) DeepCopyInto(out *ArubaCloudServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaCloudServer.
func (in *ArubaCloudServer) DeepCopy() *ArubaCloudServer {
	if in == nil {
		return nil
	}
	out := new(ArubaCloudServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaCloudServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaCloudServerList) DeepCopyInto(out *ArubaCloudServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaCloudServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaCloudServerList.
func (in *ArubaCloudServerList) DeepCopy() *ArubaCloudServerList {
	if in == nil {
		return nil
	}
	out := new(ArubaCloudServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaCloudServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaCloudServerSpec) DeepCopyInto(out *ArubaCloudServerSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.VpcReference = in.VpcReference
	if in.ElasticIpReference != nil {
		in, out := &in.ElasticIpReference, &out.ElasticIpReference
		*out = new(ResourceReference)
		**out = **in
	}
	out.KeyPairReference = in.KeyPairReference
	if in.SubnetReferences != nil {
		in, out := &in.SubnetReferences, &out.SubnetReferences
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupReferences != nil {
		in, out := &in.SecurityGroupReferences, &out.SecurityGroupReferences
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	out.BootVolumeReference = in.BootVolumeReference
	if in.DataVolumeReferences != nil {
		in, out := &in.DataVolumeReferences, &out.DataVolumeReferences
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaCloudServerSpec.
func (in *ArubaCloudServerSpec) DeepCopy() *ArubaCloudServerSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaCloudServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaCloudServerStatus) DeepCopyInto(out *ArubaCloudServerStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataVolumeIDs != nil {
		in, out := &in.DataVolumeIDs, &out.DataVolumeIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VolumeIDs != nil {
		in, out := &in.VolumeIDs, &out.VolumeIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaCloudServerStatus.
func (in *ArubaCloudServerStatus) DeepCopy() *ArubaCloudServerStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaCloudServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaKeyPair) DeepCopyInto(out *ArubaKeyPair) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaKeyPair.
func (in *ArubaKeyPair) DeepCopy() *ArubaKeyPair {
	if in == nil {
		return nil
	}
	out := new(ArubaKeyPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaKeyPair) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaKeyPairList) DeepCopyInto(out *ArubaKeyPairList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaKeyPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaKeyPairList.
func (in *ArubaKeyPairList) DeepCopy() *ArubaKeyPairList {
	if in == nil {
		return nil
	}
	out := new(ArubaKeyPairList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaKeyPairList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaKeyPairSpec) DeepCopyInto(out *ArubaKeyPairSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaKeyPairSpec.
func (in *ArubaKeyPairSpec) DeepCopy() *ArubaKeyPairSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaKeyPairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaKeyPairStatus) DeepCopyInto(out *ArubaKeyPairStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaKeyPairStatus.
func (in *ArubaKeyPairStatus) DeepCopy() *ArubaKeyPairStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaKeyPairStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaNetworkElasticIp) DeepCopyInto(out *ArubaNetworkElasticIp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaNetworkElasticIp.
func (in *ArubaNetworkElasticIp) DeepCopy() *ArubaNetworkElasticIp {
	if in == nil {
		return nil
	}
	out := new(ArubaNetworkElasticIp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaNetworkElasticIp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaNetworkElasticIpList) DeepCopyInto(out *ArubaNetworkElasticIpList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaNetworkElasticIp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaNetworkElasticIpList.
func (in *ArubaNetworkElasticIpList) DeepCopy() *ArubaNetworkElasticIpList {
	if in == nil {
		return nil
	}
	out := new(ArubaNetworkElasticIpList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaNetworkElasticIpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaNetworkElasticIpSpec) DeepCopyInto(out *ArubaNetworkElasticIpSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.BillingPlan = in.BillingPlan
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaNetworkElasticIpSpec.
func (in *ArubaNetworkElasticIpSpec) DeepCopy() *ArubaNetworkElasticIpSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaNetworkElasticIpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaNetworkElasticIpStatus) DeepCopyInto(out *ArubaNetworkElasticIpStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaNetworkElasticIpStatus.
func (in *ArubaNetworkElasticIpStatus) DeepCopy() *ArubaNetworkElasticIpStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaNetworkElasticIpStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaObject) DeepCopyInto(out *ArubaObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaObject.
func (in *ArubaObject) DeepCopy() *ArubaObject {
	if in == nil {
		return nil
	}
	out := new(ArubaObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaProject) DeepCopyInto(out *ArubaProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaProject.
func (in *ArubaProject) DeepCopy() *ArubaProject {
	if in == nil {
		return nil
	}
	out := new(ArubaProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaProjectList) DeepCopyInto(out *ArubaProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaProjectList.
func (in *ArubaProjectList) DeepCopy() *ArubaProjectList {
	if in == nil {
		return nil
	}
	out := new(ArubaProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaProjectSpec) DeepCopyInto(out *ArubaProjectSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaProjectSpec.
func (in *ArubaProjectSpec) DeepCopy() *ArubaProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaResourceStatus) DeepCopyInto(out *ArubaResourceStatus) {
	*out = *in
	if in.PhaseStartTime != nil {
		in, out := &in.PhaseStartTime, &out.PhaseStartTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaResourceStatus.
func (in *ArubaResourceStatus) DeepCopy() *ArubaResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityGroup) DeepCopyInto(out *ArubaSecurityGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityGroup.
func (in *ArubaSecurityGroup) DeepCopy() *ArubaSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaSecurityGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityGroupList) DeepCopyInto(out *ArubaSecurityGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaSecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityGroupList.
func (in *ArubaSecurityGroupList) DeepCopy() *ArubaSecurityGroupList {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaSecurityGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityGroupSpec) DeepCopyInto(out *ArubaSecurityGroupSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.VpcReference = in.VpcReference
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityGroupSpec.
func (in *ArubaSecurityGroupSpec) DeepCopy() *ArubaSecurityGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityGroupStatus) DeepCopyInto(out *ArubaSecurityGroupStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityGroupStatus.
func (in *ArubaSecurityGroupStatus) DeepCopy() *ArubaSecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityRule) DeepCopyInto(out *ArubaSecurityRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityRule.
func (in *ArubaSecurityRule) DeepCopy() *ArubaSecurityRule {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaSecurityRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityRuleList) DeepCopyInto(out *ArubaSecurityRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaSecurityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityRuleList.
func (in *ArubaSecurityRuleList) DeepCopy() *ArubaSecurityRuleList {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaSecurityRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityRuleSpec) DeepCopyInto(out *ArubaSecurityRuleSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.Target = in.Target
	out.SecurityGroupReference = in.SecurityGroupReference
	out.VpcReference = in.VpcReference
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityRuleSpec.
func (in *ArubaSecurityRuleSpec) DeepCopy() *ArubaSecurityRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSecurityRuleStatus) DeepCopyInto(out *ArubaSecurityRuleStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSecurityRuleStatus.
func (in *ArubaSecurityRuleStatus) DeepCopy() *ArubaSecurityRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaSecurityRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSubnet) DeepCopyInto(out *ArubaSubnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSubnet.
func (in *ArubaSubnet) DeepCopy() *ArubaSubnet {
	if in == nil {
		return nil
	}
	out := new(ArubaSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaSubnet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSubnetList) DeepCopyInto(out *ArubaSubnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSubnetList.
func (in *ArubaSubnetList) DeepCopy() *ArubaSubnetList {
	if in == nil {
		return nil
	}
	out := new(ArubaSubnetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaSubnetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSubnetSpec) DeepCopyInto(out *ArubaSubnetSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Network = in.Network
	out.DHCP = in.DHCP
	out.VpcReference = in.VpcReference
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSubnetSpec.
func (in *ArubaSubnetSpec) DeepCopy() *ArubaSubnetSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaSubnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaSubnetStatus) DeepCopyInto(out *ArubaSubnetStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaSubnetStatus.
func (in *ArubaSubnetStatus) DeepCopy() *ArubaSubnetStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaSubnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaVpc) DeepCopyInto(out *ArubaVpc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaVpc.
func (in *ArubaVpc) DeepCopy() *ArubaVpc {
	if in == nil {
		return nil
	}
	out := new(ArubaVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaVpc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaVpcList) DeepCopyInto(out *ArubaVpcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArubaVpc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaVpcList.
func (in *ArubaVpcList) DeepCopy() *ArubaVpcList {
	if in == nil {
		return nil
	}
	out := new(ArubaVpcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArubaVpcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaVpcSpec) DeepCopyInto(out *ArubaVpcSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Location = in.Location
	out.ProjectReference = in.ProjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaVpcSpec.
func (in *ArubaVpcSpec) DeepCopy() *ArubaVpcSpec {
	if in == nil {
		return nil
	}
	out := new(ArubaVpcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArubaVpcStatus) DeepCopyInto(out *ArubaVpcStatus) {
	*out = *in
	in.ArubaResourceStatus.DeepCopyInto(&out.ArubaResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArubaVpcStatus.
func (in *ArubaVpcStatus) DeepCopy() *ArubaVpcStatus {
	if in == nil {
		return nil
	}
	out := new(ArubaVpcStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingPlan) DeepCopyInto(out *BillingPlan) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingPlan.
func (in *BillingPlan) DeepCopy() *BillingPlan {
	if in == nil {
		return nil
	}
	out := new(BillingPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Location.
func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRuleTarget) DeepCopyInto(out *SecurityRuleTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRuleTarget.
func (in *SecurityRuleTarget) DeepCopy() *SecurityRuleTarget {
	if in == nil {
		return nil
	}
	out := new(SecurityRuleTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCP) DeepCopyInto(out *SubnetDHCP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCP.
func (in *SubnetDHCP) DeepCopy() *SubnetDHCP {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetNetwork) DeepCopyInto(out *SubnetNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetNetwork.
func (in *SubnetNetwork) DeepCopy() *SubnetNetwork {
	if in == nil {
		return nil
	}
	out := new(SubnetNetwork)
	in.DeepCopyInto(out)
	return out
}
