// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	client "github.com/Arubacloud/arubacloud-resource-operator/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// FromCompute provides a mock function with no fields
func (_m *MockClient) FromCompute() client.ComputeClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromCompute")
	}

	var r0 client.ComputeClient
	if rf, ok := ret.Get(0).(func() client.ComputeClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ComputeClient)
		}
	}

	return r0
}

// MockClient_FromCompute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromCompute'
type MockClient_FromCompute_Call struct {
	*mock.Call
}

// FromCompute is a helper method to define mock.On call
func (_e *MockClient_Expecter) FromCompute() *MockClient_FromCompute_Call {
	return &MockClient_FromCompute_Call{Call: _e.mock.On("FromCompute")}
}

func (_c *MockClient_FromCompute_Call) Run(run func()) *MockClient_FromCompute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_FromCompute_Call) Return(_a0 client.ComputeClient) *MockClient_FromCompute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_FromCompute_Call) RunAndReturn(run func() client.ComputeClient) *MockClient_FromCompute_Call {
	_c.Call.Return(run)
	return _c
}

// FromNetwork provides a mock function with no fields
func (_m *MockClient) FromNetwork() client.NetworkClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromNetwork")
	}

	var r0 client.NetworkClient
	if rf, ok := ret.Get(0).(func() client.NetworkClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.NetworkClient)
		}
	}

	return r0
}

// MockClient_FromNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromNetwork'
type MockClient_FromNetwork_Call struct {
	*mock.Call
}

// FromNetwork is a helper method to define mock.On call
func (_e *MockClient_Expecter) FromNetwork() *MockClient_FromNetwork_Call {
	return &MockClient_FromNetwork_Call{Call: _e.mock.On("FromNetwork")}
}

func (_c *MockClient_FromNetwork_Call) Run(run func()) *MockClient_FromNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_FromNetwork_Call) Return(_a0 client.NetworkClient) *MockClient_FromNetwork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_FromNetwork_Call) RunAndReturn(run func() client.NetworkClient) *MockClient_FromNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// FromProject provides a mock function with no fields
func (_m *MockClient) FromProject() client.ProjectClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromProject")
	}

	var r0 client.ProjectClient
	if rf, ok := ret.Get(0).(func() client.ProjectClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ProjectClient)
		}
	}

	return r0
}

// MockClient_FromProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromProject'
type MockClient_FromProject_Call struct {
	*mock.Call
}

// FromProject is a helper method to define mock.On call
func (_e *MockClient_Expecter) FromProject() *MockClient_FromProject_Call {
	return &MockClient_FromProject_Call{Call: _e.mock.On("FromProject")}
}

func (_c *MockClient_FromProject_Call) Run(run func()) *MockClient_FromProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_FromProject_Call) Return(_a0 client.ProjectClient) *MockClient_FromProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_FromProject_Call) RunAndReturn(run func() client.ProjectClient) *MockClient_FromProject_Call {
	_c.Call.Return(run)
	return _c
}

// FromStorage provides a mock function with no fields
func (_m *MockClient) FromStorage() client.StorageClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromStorage")
	}

	var r0 client.StorageClient
	if rf, ok := ret.Get(0).(func() client.StorageClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.StorageClient)
		}
	}

	return r0
}

// MockClient_FromStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromStorage'
type MockClient_FromStorage_Call struct {
	*mock.Call
}

// FromStorage is a helper method to define mock.On call
func (_e *MockClient_Expecter) FromStorage() *MockClient_FromStorage_Call {
	return &MockClient_FromStorage_Call{Call: _e.mock.On("FromStorage")}
}

func (_c *MockClient_FromStorage_Call) Run(run func()) *MockClient_FromStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_FromStorage_Call) Return(_a0 client.StorageClient) *MockClient_FromStorage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_FromStorage_Call) RunAndReturn(run func() client.StorageClient) *MockClient_FromStorage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
