// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockSecurityGroupRulesClient is an autogenerated mock type for the SecurityGroupRulesClient type
type MockSecurityGroupRulesClient struct {
	mock.Mock
}

type MockSecurityGroupRulesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecurityGroupRulesClient) EXPECT() *MockSecurityGroupRulesClient_Expecter {
	return &MockSecurityGroupRulesClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, body, params
func (_m *MockSecurityGroupRulesClient) Create(ctx context.Context, projectID string, vpcID string, securityGroupID string, body types.SecurityRuleRequest, params *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.SecurityRuleResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) *types.Response[types.SecurityRuleResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityRuleResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupRulesClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecurityGroupRulesClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - body types.SecurityRuleRequest
//   - params *types.RequestParameters
func (_e *MockSecurityGroupRulesClient_Expecter) Create(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, body interface{}, params interface{}) *MockSecurityGroupRulesClient_Create_Call {
	return &MockSecurityGroupRulesClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, vpcID, securityGroupID, body, params)}
}

func (_c *MockSecurityGroupRulesClient_Create_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, body types.SecurityRuleRequest, params *types.RequestParameters)) *MockSecurityGroupRulesClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(types.SecurityRuleRequest), args[5].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupRulesClient_Create_Call) Return(_a0 *types.Response[types.SecurityRuleResponse], _a1 error) *MockSecurityGroupRulesClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupRulesClient_Create_Call) RunAndReturn(run func(context.Context, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error)) *MockSecurityGroupRulesClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params
func (_m *MockSecurityGroupRulesClient) Delete(ctx context.Context, projectID string, vpcID string, securityGroupID string, securityGroupRuleID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupRulesClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecurityGroupRulesClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - securityGroupRuleID string
//   - params *types.RequestParameters
func (_e *MockSecurityGroupRulesClient_Expecter) Delete(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, securityGroupRuleID interface{}, params interface{}) *MockSecurityGroupRulesClient_Delete_Call {
	return &MockSecurityGroupRulesClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)}
}

func (_c *MockSecurityGroupRulesClient_Delete_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, securityGroupRuleID string, params *types.RequestParameters)) *MockSecurityGroupRulesClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupRulesClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockSecurityGroupRulesClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupRulesClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockSecurityGroupRulesClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params
func (_m *MockSecurityGroupRulesClient) Get(ctx context.Context, projectID string, vpcID string, securityGroupID string, securityGroupRuleID string, params *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Response[types.SecurityRuleResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *types.RequestParameters) *types.Response[types.SecurityRuleResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityRuleResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupRulesClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecurityGroupRulesClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - securityGroupRuleID string
//   - params *types.RequestParameters
func (_e *MockSecurityGroupRulesClient_Expecter) Get(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, securityGroupRuleID interface{}, params interface{}) *MockSecurityGroupRulesClient_Get_Call {
	return &MockSecurityGroupRulesClient_Get_Call{Call: _e.mock.On("Get", ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, params)}
}

func (_c *MockSecurityGroupRulesClient_Get_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, securityGroupRuleID string, params *types.RequestParameters)) *MockSecurityGroupRulesClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupRulesClient_Get_Call) Return(_a0 *types.Response[types.SecurityRuleResponse], _a1 error) *MockSecurityGroupRulesClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupRulesClient_Get_Call) RunAndReturn(run func(context.Context, string, string, string, string, *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error)) *MockSecurityGroupRulesClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, params
func (_m *MockSecurityGroupRulesClient) List(ctx context.Context, projectID string, vpcID string, securityGroupID string, params *types.RequestParameters) (*types.Response[types.SecurityRuleList], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.SecurityRuleList]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[types.SecurityRuleList], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) *types.Response[types.SecurityRuleList]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityRuleList])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupRulesClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecurityGroupRulesClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - params *types.RequestParameters
func (_e *MockSecurityGroupRulesClient_Expecter) List(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, params interface{}) *MockSecurityGroupRulesClient_List_Call {
	return &MockSecurityGroupRulesClient_List_Call{Call: _e.mock.On("List", ctx, projectID, vpcID, securityGroupID, params)}
}

func (_c *MockSecurityGroupRulesClient_List_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, params *types.RequestParameters)) *MockSecurityGroupRulesClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupRulesClient_List_Call) Return(_a0 *types.Response[types.SecurityRuleList], _a1 error) *MockSecurityGroupRulesClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupRulesClient_List_Call) RunAndReturn(run func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[types.SecurityRuleList], error)) *MockSecurityGroupRulesClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, body, params
func (_m *MockSecurityGroupRulesClient) Update(ctx context.Context, projectID string, vpcID string, securityGroupID string, securityGroupRuleID string, body types.SecurityRuleRequest, params *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.SecurityRuleResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) *types.Response[types.SecurityRuleResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityRuleResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupRulesClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSecurityGroupRulesClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - securityGroupRuleID string
//   - body types.SecurityRuleRequest
//   - params *types.RequestParameters
func (_e *MockSecurityGroupRulesClient_Expecter) Update(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, securityGroupRuleID interface{}, body interface{}, params interface{}) *MockSecurityGroupRulesClient_Update_Call {
	return &MockSecurityGroupRulesClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, vpcID, securityGroupID, securityGroupRuleID, body, params)}
}

func (_c *MockSecurityGroupRulesClient_Update_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, securityGroupRuleID string, body types.SecurityRuleRequest, params *types.RequestParameters)) *MockSecurityGroupRulesClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(types.SecurityRuleRequest), args[6].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupRulesClient_Update_Call) Return(_a0 *types.Response[types.SecurityRuleResponse], _a1 error) *MockSecurityGroupRulesClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupRulesClient_Update_Call) RunAndReturn(run func(context.Context, string, string, string, string, types.SecurityRuleRequest, *types.RequestParameters) (*types.Response[types.SecurityRuleResponse], error)) *MockSecurityGroupRulesClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecurityGroupRulesClient creates a new instance of MockSecurityGroupRulesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecurityGroupRulesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecurityGroupRulesClient {
	mock := &MockSecurityGroupRulesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
