// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockKeyPairsClient is an autogenerated mock type for the KeyPairsClient type
type MockKeyPairsClient struct {
	mock.Mock
}

type MockKeyPairsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyPairsClient) EXPECT() *MockKeyPairsClient_Expecter {
	return &MockKeyPairsClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, body, params
func (_m *MockKeyPairsClient) Create(ctx context.Context, projectID string, body types.KeyPairRequest, params *types.RequestParameters) (*types.Response[types.KeyPairResponse], error) {
	ret := _m.Called(ctx, projectID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.KeyPairResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.KeyPairRequest, *types.RequestParameters) (*types.Response[types.KeyPairResponse], error)); ok {
		return rf(ctx, projectID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.KeyPairRequest, *types.RequestParameters) *types.Response[types.KeyPairResponse]); ok {
		r0 = rf(ctx, projectID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.KeyPairResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.KeyPairRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyPairsClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyPairsClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - body types.KeyPairRequest
//   - params *types.RequestParameters
func (_e *MockKeyPairsClient_Expecter) Create(ctx interface{}, projectID interface{}, body interface{}, params interface{}) *MockKeyPairsClient_Create_Call {
	return &MockKeyPairsClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, body, params)}
}

func (_c *MockKeyPairsClient_Create_Call) Run(run func(ctx context.Context, projectID string, body types.KeyPairRequest, params *types.RequestParameters)) *MockKeyPairsClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.KeyPairRequest), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockKeyPairsClient_Create_Call) Return(_a0 *types.Response[types.KeyPairResponse], _a1 error) *MockKeyPairsClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyPairsClient_Create_Call) RunAndReturn(run func(context.Context, string, types.KeyPairRequest, *types.RequestParameters) (*types.Response[types.KeyPairResponse], error)) *MockKeyPairsClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, keyPairID, params
func (_m *MockKeyPairsClient) Delete(ctx context.Context, projectID string, keyPairID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, keyPairID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, keyPairID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, keyPairID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, keyPairID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyPairsClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeyPairsClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - keyPairID string
//   - params *types.RequestParameters
func (_e *MockKeyPairsClient_Expecter) Delete(ctx interface{}, projectID interface{}, keyPairID interface{}, params interface{}) *MockKeyPairsClient_Delete_Call {
	return &MockKeyPairsClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, keyPairID, params)}
}

func (_c *MockKeyPairsClient_Delete_Call) Run(run func(ctx context.Context, projectID string, keyPairID string, params *types.RequestParameters)) *MockKeyPairsClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockKeyPairsClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockKeyPairsClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyPairsClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockKeyPairsClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, params
func (_m *MockKeyPairsClient) List(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[types.KeyPairListResponse], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.KeyPairListResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[types.KeyPairListResponse], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[types.KeyPairListResponse]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.KeyPairListResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyPairsClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeyPairsClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockKeyPairsClient_Expecter) List(ctx interface{}, projectID interface{}, params interface{}) *MockKeyPairsClient_List_Call {
	return &MockKeyPairsClient_List_Call{Call: _e.mock.On("List", ctx, projectID, params)}
}

func (_c *MockKeyPairsClient_List_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockKeyPairsClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockKeyPairsClient_List_Call) Return(_a0 *types.Response[types.KeyPairListResponse], _a1 error) *MockKeyPairsClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyPairsClient_List_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[types.KeyPairListResponse], error)) *MockKeyPairsClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyPairsClient creates a new instance of MockKeyPairsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyPairsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyPairsClient {
	mock := &MockKeyPairsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
