// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	client "github.com/Arubacloud/arubacloud-resource-operator/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// MockComputeClient is an autogenerated mock type for the ComputeClient type
type MockComputeClient struct {
	mock.Mock
}

type MockComputeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComputeClient) EXPECT() *MockComputeClient_Expecter {
	return &MockComputeClient_Expecter{mock: &_m.Mock}
}

// CloudServers provides a mock function with no fields
func (_m *MockComputeClient) CloudServers() client.CloudServersClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloudServers")
	}

	var r0 client.CloudServersClient
	if rf, ok := ret.Get(0).(func() client.CloudServersClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.CloudServersClient)
		}
	}

	return r0
}

// MockComputeClient_CloudServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloudServers'
type MockComputeClient_CloudServers_Call struct {
	*mock.Call
}

// CloudServers is a helper method to define mock.On call
func (_e *MockComputeClient_Expecter) CloudServers() *MockComputeClient_CloudServers_Call {
	return &MockComputeClient_CloudServers_Call{Call: _e.mock.On("CloudServers")}
}

func (_c *MockComputeClient_CloudServers_Call) Run(run func()) *MockComputeClient_CloudServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComputeClient_CloudServers_Call) Return(_a0 client.CloudServersClient) *MockComputeClient_CloudServers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComputeClient_CloudServers_Call) RunAndReturn(run func() client.CloudServersClient) *MockComputeClient_CloudServers_Call {
	_c.Call.Return(run)
	return _c
}

// KeyPairs provides a mock function with no fields
func (_m *MockComputeClient) KeyPairs() client.KeyPairsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for KeyPairs")
	}

	var r0 client.KeyPairsClient
	if rf, ok := ret.Get(0).(func() client.KeyPairsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.KeyPairsClient)
		}
	}

	return r0
}

// MockComputeClient_KeyPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyPairs'
type MockComputeClient_KeyPairs_Call struct {
	*mock.Call
}

// KeyPairs is a helper method to define mock.On call
func (_e *MockComputeClient_Expecter) KeyPairs() *MockComputeClient_KeyPairs_Call {
	return &MockComputeClient_KeyPairs_Call{Call: _e.mock.On("KeyPairs")}
}

func (_c *MockComputeClient_KeyPairs_Call) Run(run func()) *MockComputeClient_KeyPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComputeClient_KeyPairs_Call) Return(_a0 client.KeyPairsClient) *MockComputeClient_KeyPairs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComputeClient_KeyPairs_Call) RunAndReturn(run func() client.KeyPairsClient) *MockComputeClient_KeyPairs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComputeClient creates a new instance of MockComputeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComputeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComputeClient {
	mock := &MockComputeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
