// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	aruba "github.com/Arubacloud/sdk-go/pkg/aruba"
	mock "github.com/stretchr/testify/mock"
)

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// Backups provides a mock function with no fields
func (_m *MockStorageClient) Backups() aruba.StorageBackupsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Backups")
	}

	var r0 aruba.StorageBackupsClient
	if rf, ok := ret.Get(0).(func() aruba.StorageBackupsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.StorageBackupsClient)
		}
	}

	return r0
}

// MockStorageClient_Backups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backups'
type MockStorageClient_Backups_Call struct {
	*mock.Call
}

// Backups is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) Backups() *MockStorageClient_Backups_Call {
	return &MockStorageClient_Backups_Call{Call: _e.mock.On("Backups")}
}

func (_c *MockStorageClient_Backups_Call) Run(run func()) *MockStorageClient_Backups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_Backups_Call) Return(_a0 aruba.StorageBackupsClient) *MockStorageClient_Backups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Backups_Call) RunAndReturn(run func() aruba.StorageBackupsClient) *MockStorageClient_Backups_Call {
	_c.Call.Return(run)
	return _c
}

// Restores provides a mock function with no fields
func (_m *MockStorageClient) Restores() aruba.StorageRestoreClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Restores")
	}

	var r0 aruba.StorageRestoreClient
	if rf, ok := ret.Get(0).(func() aruba.StorageRestoreClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.StorageRestoreClient)
		}
	}

	return r0
}

// MockStorageClient_Restores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restores'
type MockStorageClient_Restores_Call struct {
	*mock.Call
}

// Restores is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) Restores() *MockStorageClient_Restores_Call {
	return &MockStorageClient_Restores_Call{Call: _e.mock.On("Restores")}
}

func (_c *MockStorageClient_Restores_Call) Run(run func()) *MockStorageClient_Restores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_Restores_Call) Return(_a0 aruba.StorageRestoreClient) *MockStorageClient_Restores_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Restores_Call) RunAndReturn(run func() aruba.StorageRestoreClient) *MockStorageClient_Restores_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshots provides a mock function with no fields
func (_m *MockStorageClient) Snapshots() aruba.SnapshotsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshots")
	}

	var r0 aruba.SnapshotsClient
	if rf, ok := ret.Get(0).(func() aruba.SnapshotsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.SnapshotsClient)
		}
	}

	return r0
}

// MockStorageClient_Snapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshots'
type MockStorageClient_Snapshots_Call struct {
	*mock.Call
}

// Snapshots is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) Snapshots() *MockStorageClient_Snapshots_Call {
	return &MockStorageClient_Snapshots_Call{Call: _e.mock.On("Snapshots")}
}

func (_c *MockStorageClient_Snapshots_Call) Run(run func()) *MockStorageClient_Snapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_Snapshots_Call) Return(_a0 aruba.SnapshotsClient) *MockStorageClient_Snapshots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Snapshots_Call) RunAndReturn(run func() aruba.SnapshotsClient) *MockStorageClient_Snapshots_Call {
	_c.Call.Return(run)
	return _c
}

// Volumes provides a mock function with no fields
func (_m *MockStorageClient) Volumes() aruba.VolumesClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Volumes")
	}

	var r0 aruba.VolumesClient
	if rf, ok := ret.Get(0).(func() aruba.VolumesClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.VolumesClient)
		}
	}

	return r0
}

// MockStorageClient_Volumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Volumes'
type MockStorageClient_Volumes_Call struct {
	*mock.Call
}

// Volumes is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) Volumes() *MockStorageClient_Volumes_Call {
	return &MockStorageClient_Volumes_Call{Call: _e.mock.On("Volumes")}
}

func (_c *MockStorageClient_Volumes_Call) Run(run func()) *MockStorageClient_Volumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_Volumes_Call) Return(_a0 aruba.VolumesClient) *MockStorageClient_Volumes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Volumes_Call) RunAndReturn(run func() aruba.VolumesClient) *MockStorageClient_Volumes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
