// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	client "github.com/Arubacloud/arubacloud-resource-operator/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// MockNetworkClient is an autogenerated mock type for the NetworkClient type
type MockNetworkClient struct {
	mock.Mock
}

type MockNetworkClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkClient) EXPECT() *MockNetworkClient_Expecter {
	return &MockNetworkClient_Expecter{mock: &_m.Mock}
}

// ElasticIPs provides a mock function with no fields
func (_m *MockNetworkClient) ElasticIPs() client.ElasticIPsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ElasticIPs")
	}

	var r0 client.ElasticIPsClient
	if rf, ok := ret.Get(0).(func() client.ElasticIPsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ElasticIPsClient)
		}
	}

	return r0
}

// MockNetworkClient_ElasticIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ElasticIPs'
type MockNetworkClient_ElasticIPs_Call struct {
	*mock.Call
}

// ElasticIPs is a helper method to define mock.On call
func (_e *MockNetworkClient_Expecter) ElasticIPs() *MockNetworkClient_ElasticIPs_Call {
	return &MockNetworkClient_ElasticIPs_Call{Call: _e.mock.On("ElasticIPs")}
}

func (_c *MockNetworkClient_ElasticIPs_Call) Run(run func()) *MockNetworkClient_ElasticIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkClient_ElasticIPs_Call) Return(_a0 client.ElasticIPsClient) *MockNetworkClient_ElasticIPs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkClient_ElasticIPs_Call) RunAndReturn(run func() client.ElasticIPsClient) *MockNetworkClient_ElasticIPs_Call {
	_c.Call.Return(run)
	return _c
}

// SecurityGroupRules provides a mock function with no fields
func (_m *MockNetworkClient) SecurityGroupRules() client.SecurityGroupRulesClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SecurityGroupRules")
	}

	var r0 client.SecurityGroupRulesClient
	if rf, ok := ret.Get(0).(func() client.SecurityGroupRulesClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SecurityGroupRulesClient)
		}
	}

	return r0
}

// MockNetworkClient_SecurityGroupRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecurityGroupRules'
type MockNetworkClient_SecurityGroupRules_Call struct {
	*mock.Call
}

// SecurityGroupRules is a helper method to define mock.On call
func (_e *MockNetworkClient_Expecter) SecurityGroupRules() *MockNetworkClient_SecurityGroupRules_Call {
	return &MockNetworkClient_SecurityGroupRules_Call{Call: _e.mock.On("SecurityGroupRules")}
}

func (_c *MockNetworkClient_SecurityGroupRules_Call) Run(run func()) *MockNetworkClient_SecurityGroupRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkClient_SecurityGroupRules_Call) Return(_a0 client.SecurityGroupRulesClient) *MockNetworkClient_SecurityGroupRules_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkClient_SecurityGroupRules_Call) RunAndReturn(run func() client.SecurityGroupRulesClient) *MockNetworkClient_SecurityGroupRules_Call {
	_c.Call.Return(run)
	return _c
}

// SecurityGroups provides a mock function with no fields
func (_m *MockNetworkClient) SecurityGroups() client.SecurityGroupsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SecurityGroups")
	}

	var r0 client.SecurityGroupsClient
	if rf, ok := ret.Get(0).(func() client.SecurityGroupsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SecurityGroupsClient)
		}
	}

	return r0
}

// MockNetworkClient_SecurityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecurityGroups'
type MockNetworkClient_SecurityGroups_Call struct {
	*mock.Call
}

// SecurityGroups is a helper method to define mock.On call
func (_e *MockNetworkClient_Expecter) SecurityGroups() *MockNetworkClient_SecurityGroups_Call {
	return &MockNetworkClient_SecurityGroups_Call{Call: _e.mock.On("SecurityGroups")}
}

func (_c *MockNetworkClient_SecurityGroups_Call) Run(run func()) *MockNetworkClient_SecurityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkClient_SecurityGroups_Call) Return(_a0 client.SecurityGroupsClient) *MockNetworkClient_SecurityGroups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkClient_SecurityGroups_Call) RunAndReturn(run func() client.SecurityGroupsClient) *MockNetworkClient_SecurityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// Subnets provides a mock function with no fields
func (_m *MockNetworkClient) Subnets() client.SubnetsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subnets")
	}

	var r0 client.SubnetsClient
	if rf, ok := ret.Get(0).(func() client.SubnetsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SubnetsClient)
		}
	}

	return r0
}

// MockNetworkClient_Subnets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subnets'
type MockNetworkClient_Subnets_Call struct {
	*mock.Call
}

// Subnets is a helper method to define mock.On call
func (_e *MockNetworkClient_Expecter) Subnets() *MockNetworkClient_Subnets_Call {
	return &MockNetworkClient_Subnets_Call{Call: _e.mock.On("Subnets")}
}

func (_c *MockNetworkClient_Subnets_Call) Run(run func()) *MockNetworkClient_Subnets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkClient_Subnets_Call) Return(_a0 client.SubnetsClient) *MockNetworkClient_Subnets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkClient_Subnets_Call) RunAndReturn(run func() client.SubnetsClient) *MockNetworkClient_Subnets_Call {
	_c.Call.Return(run)
	return _c
}

// VPCs provides a mock function with no fields
func (_m *MockNetworkClient) VPCs() client.VPCsClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VPCs")
	}

	var r0 client.VPCsClient
	if rf, ok := ret.Get(0).(func() client.VPCsClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.VPCsClient)
		}
	}

	return r0
}

// MockNetworkClient_VPCs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VPCs'
type MockNetworkClient_VPCs_Call struct {
	*mock.Call
}

// VPCs is a helper method to define mock.On call
func (_e *MockNetworkClient_Expecter) VPCs() *MockNetworkClient_VPCs_Call {
	return &MockNetworkClient_VPCs_Call{Call: _e.mock.On("VPCs")}
}

func (_c *MockNetworkClient_VPCs_Call) Run(run func()) *MockNetworkClient_VPCs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkClient_VPCs_Call) Return(_a0 client.VPCsClient) *MockNetworkClient_VPCs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkClient_VPCs_Call) RunAndReturn(run func() client.VPCsClient) *MockNetworkClient_VPCs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNetworkClient creates a new instance of MockNetworkClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkClient {
	mock := &MockNetworkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
