// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockCloudServersClient is an autogenerated mock type for the CloudServersClient type
type MockCloudServersClient struct {
	mock.Mock
}

type MockCloudServersClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudServersClient) EXPECT() *MockCloudServersClient_Expecter {
	return &MockCloudServersClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, body, params
func (_m *MockCloudServersClient) Create(ctx context.Context, projectID string, body types.CloudServerRequest, params *types.RequestParameters) (*types.Response[types.CloudServerResponse], error) {
	ret := _m.Called(ctx, projectID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.CloudServerResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.CloudServerRequest, *types.RequestParameters) (*types.Response[types.CloudServerResponse], error)); ok {
		return rf(ctx, projectID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.CloudServerRequest, *types.RequestParameters) *types.Response[types.CloudServerResponse]); ok {
		r0 = rf(ctx, projectID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.CloudServerResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.CloudServerRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCloudServersClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCloudServersClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - body types.CloudServerRequest
//   - params *types.RequestParameters
func (_e *MockCloudServersClient_Expecter) Create(ctx interface{}, projectID interface{}, body interface{}, params interface{}) *MockCloudServersClient_Create_Call {
	return &MockCloudServersClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, body, params)}
}

func (_c *MockCloudServersClient_Create_Call) Run(run func(ctx context.Context, projectID string, body types.CloudServerRequest, params *types.RequestParameters)) *MockCloudServersClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.CloudServerRequest), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockCloudServersClient_Create_Call) Return(_a0 *types.Response[types.CloudServerResponse], _a1 error) *MockCloudServersClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCloudServersClient_Create_Call) RunAndReturn(run func(context.Context, string, types.CloudServerRequest, *types.RequestParameters) (*types.Response[types.CloudServerResponse], error)) *MockCloudServersClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, cloudServerID, params
func (_m *MockCloudServersClient) Delete(ctx context.Context, projectID string, cloudServerID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, cloudServerID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, cloudServerID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, cloudServerID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, cloudServerID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCloudServersClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCloudServersClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - cloudServerID string
//   - params *types.RequestParameters
func (_e *MockCloudServersClient_Expecter) Delete(ctx interface{}, projectID interface{}, cloudServerID interface{}, params interface{}) *MockCloudServersClient_Delete_Call {
	return &MockCloudServersClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, cloudServerID, params)}
}

func (_c *MockCloudServersClient_Delete_Call) Run(run func(ctx context.Context, projectID string, cloudServerID string, params *types.RequestParameters)) *MockCloudServersClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockCloudServersClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockCloudServersClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCloudServersClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockCloudServersClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, params
func (_m *MockCloudServersClient) List(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[types.CloudServerListResponse], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.CloudServerListResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[types.CloudServerListResponse], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[types.CloudServerListResponse]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.CloudServerListResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCloudServersClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCloudServersClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockCloudServersClient_Expecter) List(ctx interface{}, projectID interface{}, params interface{}) *MockCloudServersClient_List_Call {
	return &MockCloudServersClient_List_Call{Call: _e.mock.On("List", ctx, projectID, params)}
}

func (_c *MockCloudServersClient_List_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockCloudServersClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockCloudServersClient_List_Call) Return(_a0 *types.Response[types.CloudServerListResponse], _a1 error) *MockCloudServersClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCloudServersClient_List_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[types.CloudServerListResponse], error)) *MockCloudServersClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, cloudServerID, body, params
func (_m *MockCloudServersClient) Update(ctx context.Context, projectID string, cloudServerID string, body types.CloudServerRequest, params *types.RequestParameters) (*types.Response[types.CloudServerResponse], error) {
	ret := _m.Called(ctx, projectID, cloudServerID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.CloudServerResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.CloudServerRequest, *types.RequestParameters) (*types.Response[types.CloudServerResponse], error)); ok {
		return rf(ctx, projectID, cloudServerID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.CloudServerRequest, *types.RequestParameters) *types.Response[types.CloudServerResponse]); ok {
		r0 = rf(ctx, projectID, cloudServerID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.CloudServerResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, types.CloudServerRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, cloudServerID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCloudServersClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCloudServersClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - cloudServerID string
//   - body types.CloudServerRequest
//   - params *types.RequestParameters
func (_e *MockCloudServersClient_Expecter) Update(ctx interface{}, projectID interface{}, cloudServerID interface{}, body interface{}, params interface{}) *MockCloudServersClient_Update_Call {
	return &MockCloudServersClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, cloudServerID, body, params)}
}

func (_c *MockCloudServersClient_Update_Call) Run(run func(ctx context.Context, projectID string, cloudServerID string, body types.CloudServerRequest, params *types.RequestParameters)) *MockCloudServersClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(types.CloudServerRequest), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockCloudServersClient_Update_Call) Return(_a0 *types.Response[types.CloudServerResponse], _a1 error) *MockCloudServersClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCloudServersClient_Update_Call) RunAndReturn(run func(context.Context, string, string, types.CloudServerRequest, *types.RequestParameters) (*types.Response[types.CloudServerResponse], error)) *MockCloudServersClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCloudServersClient creates a new instance of MockCloudServersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudServersClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudServersClient {
	mock := &MockCloudServersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
