// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockSecurityGroupsClient is an autogenerated mock type for the SecurityGroupsClient type
type MockSecurityGroupsClient struct {
	mock.Mock
}

type MockSecurityGroupsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecurityGroupsClient) EXPECT() *MockSecurityGroupsClient_Expecter {
	return &MockSecurityGroupsClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, vpcID, body, params
func (_m *MockSecurityGroupsClient) Create(ctx context.Context, projectID string, vpcID string, body types.SecurityGroupRequest, params *types.RequestParameters) (*types.Response[types.SecurityGroupResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.SecurityGroupResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.SecurityGroupRequest, *types.RequestParameters) (*types.Response[types.SecurityGroupResponse], error)); ok {
		return rf(ctx, projectID, vpcID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.SecurityGroupRequest, *types.RequestParameters) *types.Response[types.SecurityGroupResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityGroupResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, types.SecurityGroupRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupsClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecurityGroupsClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - body types.SecurityGroupRequest
//   - params *types.RequestParameters
func (_e *MockSecurityGroupsClient_Expecter) Create(ctx interface{}, projectID interface{}, vpcID interface{}, body interface{}, params interface{}) *MockSecurityGroupsClient_Create_Call {
	return &MockSecurityGroupsClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, vpcID, body, params)}
}

func (_c *MockSecurityGroupsClient_Create_Call) Run(run func(ctx context.Context, projectID string, vpcID string, body types.SecurityGroupRequest, params *types.RequestParameters)) *MockSecurityGroupsClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(types.SecurityGroupRequest), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupsClient_Create_Call) Return(_a0 *types.Response[types.SecurityGroupResponse], _a1 error) *MockSecurityGroupsClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupsClient_Create_Call) RunAndReturn(run func(context.Context, string, string, types.SecurityGroupRequest, *types.RequestParameters) (*types.Response[types.SecurityGroupResponse], error)) *MockSecurityGroupsClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, params
func (_m *MockSecurityGroupsClient) Delete(ctx context.Context, projectID string, vpcID string, securityGroupID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupsClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecurityGroupsClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - params *types.RequestParameters
func (_e *MockSecurityGroupsClient_Expecter) Delete(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, params interface{}) *MockSecurityGroupsClient_Delete_Call {
	return &MockSecurityGroupsClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, vpcID, securityGroupID, params)}
}

func (_c *MockSecurityGroupsClient_Delete_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, params *types.RequestParameters)) *MockSecurityGroupsClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupsClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockSecurityGroupsClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupsClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockSecurityGroupsClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, vpcID, params
func (_m *MockSecurityGroupsClient) List(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters) (*types.Response[types.SecurityGroupListResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.SecurityGroupListResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.SecurityGroupListResponse], error)); ok {
		return rf(ctx, projectID, vpcID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[types.SecurityGroupListResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityGroupListResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupsClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecurityGroupsClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - params *types.RequestParameters
func (_e *MockSecurityGroupsClient_Expecter) List(ctx interface{}, projectID interface{}, vpcID interface{}, params interface{}) *MockSecurityGroupsClient_List_Call {
	return &MockSecurityGroupsClient_List_Call{Call: _e.mock.On("List", ctx, projectID, vpcID, params)}
}

func (_c *MockSecurityGroupsClient_List_Call) Run(run func(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters)) *MockSecurityGroupsClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupsClient_List_Call) Return(_a0 *types.Response[types.SecurityGroupListResponse], _a1 error) *MockSecurityGroupsClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupsClient_List_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.SecurityGroupListResponse], error)) *MockSecurityGroupsClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, vpcID, securityGroupID, body, params
func (_m *MockSecurityGroupsClient) Update(ctx context.Context, projectID string, vpcID string, securityGroupID string, body types.SecurityGroupRequest, params *types.RequestParameters) (*types.Response[types.SecurityGroupResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, securityGroupID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.SecurityGroupResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, types.SecurityGroupRequest, *types.RequestParameters) (*types.Response[types.SecurityGroupResponse], error)); ok {
		return rf(ctx, projectID, vpcID, securityGroupID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, types.SecurityGroupRequest, *types.RequestParameters) *types.Response[types.SecurityGroupResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, securityGroupID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SecurityGroupResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, types.SecurityGroupRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, securityGroupID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecurityGroupsClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSecurityGroupsClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - securityGroupID string
//   - body types.SecurityGroupRequest
//   - params *types.RequestParameters
func (_e *MockSecurityGroupsClient_Expecter) Update(ctx interface{}, projectID interface{}, vpcID interface{}, securityGroupID interface{}, body interface{}, params interface{}) *MockSecurityGroupsClient_Update_Call {
	return &MockSecurityGroupsClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, vpcID, securityGroupID, body, params)}
}

func (_c *MockSecurityGroupsClient_Update_Call) Run(run func(ctx context.Context, projectID string, vpcID string, securityGroupID string, body types.SecurityGroupRequest, params *types.RequestParameters)) *MockSecurityGroupsClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(types.SecurityGroupRequest), args[5].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSecurityGroupsClient_Update_Call) Return(_a0 *types.Response[types.SecurityGroupResponse], _a1 error) *MockSecurityGroupsClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecurityGroupsClient_Update_Call) RunAndReturn(run func(context.Context, string, string, string, types.SecurityGroupRequest, *types.RequestParameters) (*types.Response[types.SecurityGroupResponse], error)) *MockSecurityGroupsClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecurityGroupsClient creates a new instance of MockSecurityGroupsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecurityGroupsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecurityGroupsClient {
	mock := &MockSecurityGroupsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
