// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	client "github.com/Arubacloud/arubacloud-resource-operator/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// Volumes provides a mock function with no fields
func (_m *MockStorageClient) Volumes() client.VolumesClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Volumes")
	}

	var r0 client.VolumesClient
	if rf, ok := ret.Get(0).(func() client.VolumesClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.VolumesClient)
		}
	}

	return r0
}

// MockStorageClient_Volumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Volumes'
type MockStorageClient_Volumes_Call struct {
	*mock.Call
}

// Volumes is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) Volumes() *MockStorageClient_Volumes_Call {
	return &MockStorageClient_Volumes_Call{Call: _e.mock.On("Volumes")}
}

func (_c *MockStorageClient_Volumes_Call) Run(run func()) *MockStorageClient_Volumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_Volumes_Call) Return(_a0 client.VolumesClient) *MockStorageClient_Volumes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Volumes_Call) RunAndReturn(run func() client.VolumesClient) *MockStorageClient_Volumes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
