// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockVPCsClient is an autogenerated mock type for the VPCsClient type
type MockVPCsClient struct {
	mock.Mock
}

type MockVPCsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVPCsClient) EXPECT() *MockVPCsClient_Expecter {
	return &MockVPCsClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, body, params
func (_m *MockVPCsClient) Create(ctx context.Context, projectID string, body types.VPCRequest, params *types.RequestParameters) (*types.Response[types.VPCResponse], error) {
	ret := _m.Called(ctx, projectID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.VPCResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.VPCRequest, *types.RequestParameters) (*types.Response[types.VPCResponse], error)); ok {
		return rf(ctx, projectID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.VPCRequest, *types.RequestParameters) *types.Response[types.VPCResponse]); ok {
		r0 = rf(ctx, projectID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.VPCResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.VPCRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVPCsClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVPCsClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - body types.VPCRequest
//   - params *types.RequestParameters
func (_e *MockVPCsClient_Expecter) Create(ctx interface{}, projectID interface{}, body interface{}, params interface{}) *MockVPCsClient_Create_Call {
	return &MockVPCsClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, body, params)}
}

func (_c *MockVPCsClient_Create_Call) Run(run func(ctx context.Context, projectID string, body types.VPCRequest, params *types.RequestParameters)) *MockVPCsClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.VPCRequest), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVPCsClient_Create_Call) Return(_a0 *types.Response[types.VPCResponse], _a1 error) *MockVPCsClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVPCsClient_Create_Call) RunAndReturn(run func(context.Context, string, types.VPCRequest, *types.RequestParameters) (*types.Response[types.VPCResponse], error)) *MockVPCsClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, vpcID, params
func (_m *MockVPCsClient) Delete(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, vpcID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, vpcID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, vpcID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVPCsClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVPCsClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - params *types.RequestParameters
func (_e *MockVPCsClient_Expecter) Delete(ctx interface{}, projectID interface{}, vpcID interface{}, params interface{}) *MockVPCsClient_Delete_Call {
	return &MockVPCsClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, vpcID, params)}
}

func (_c *MockVPCsClient_Delete_Call) Run(run func(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters)) *MockVPCsClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVPCsClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockVPCsClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVPCsClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockVPCsClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, projectID, vpcID, params
func (_m *MockVPCsClient) Get(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters) (*types.Response[types.VPCResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Response[types.VPCResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.VPCResponse], error)); ok {
		return rf(ctx, projectID, vpcID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[types.VPCResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.VPCResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVPCsClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVPCsClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - params *types.RequestParameters
func (_e *MockVPCsClient_Expecter) Get(ctx interface{}, projectID interface{}, vpcID interface{}, params interface{}) *MockVPCsClient_Get_Call {
	return &MockVPCsClient_Get_Call{Call: _e.mock.On("Get", ctx, projectID, vpcID, params)}
}

func (_c *MockVPCsClient_Get_Call) Run(run func(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters)) *MockVPCsClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVPCsClient_Get_Call) Return(_a0 *types.Response[types.VPCResponse], _a1 error) *MockVPCsClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVPCsClient_Get_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.VPCResponse], error)) *MockVPCsClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, params
func (_m *MockVPCsClient) List(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[types.VPCList], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.VPCList]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[types.VPCList], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[types.VPCList]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.VPCList])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVPCsClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVPCsClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockVPCsClient_Expecter) List(ctx interface{}, projectID interface{}, params interface{}) *MockVPCsClient_List_Call {
	return &MockVPCsClient_List_Call{Call: _e.mock.On("List", ctx, projectID, params)}
}

func (_c *MockVPCsClient_List_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockVPCsClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVPCsClient_List_Call) Return(_a0 *types.Response[types.VPCList], _a1 error) *MockVPCsClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVPCsClient_List_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[types.VPCList], error)) *MockVPCsClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, vpcID, body, params
func (_m *MockVPCsClient) Update(ctx context.Context, projectID string, vpcID string, body types.VPCRequest, params *types.RequestParameters) (*types.Response[types.VPCResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.VPCResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.VPCRequest, *types.RequestParameters) (*types.Response[types.VPCResponse], error)); ok {
		return rf(ctx, projectID, vpcID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.VPCRequest, *types.RequestParameters) *types.Response[types.VPCResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.VPCResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, types.VPCRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVPCsClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVPCsClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - body types.VPCRequest
//   - params *types.RequestParameters
func (_e *MockVPCsClient_Expecter) Update(ctx interface{}, projectID interface{}, vpcID interface{}, body interface{}, params interface{}) *MockVPCsClient_Update_Call {
	return &MockVPCsClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, vpcID, body, params)}
}

func (_c *MockVPCsClient_Update_Call) Run(run func(ctx context.Context, projectID string, vpcID string, body types.VPCRequest, params *types.RequestParameters)) *MockVPCsClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(types.VPCRequest), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVPCsClient_Update_Call) Return(_a0 *types.Response[types.VPCResponse], _a1 error) *MockVPCsClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVPCsClient_Update_Call) RunAndReturn(run func(context.Context, string, string, types.VPCRequest, *types.RequestParameters) (*types.Response[types.VPCResponse], error)) *MockVPCsClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVPCsClient creates a new instance of MockVPCsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVPCsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVPCsClient {
	mock := &MockVPCsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
