// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockProjectClient is an autogenerated mock type for the ProjectClient type
type MockProjectClient struct {
	mock.Mock
}

type MockProjectClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectClient) EXPECT() *MockProjectClient_Expecter {
	return &MockProjectClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, body, params
func (_m *MockProjectClient) Create(ctx context.Context, body types.ProjectRequest, params *types.RequestParameters) (*types.Response[types.ProjectResponse], error) {
	ret := _m.Called(ctx, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.ProjectResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ProjectRequest, *types.RequestParameters) (*types.Response[types.ProjectResponse], error)); ok {
		return rf(ctx, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ProjectRequest, *types.RequestParameters) *types.Response[types.ProjectResponse]); ok {
		r0 = rf(ctx, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ProjectResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ProjectRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - body types.ProjectRequest
//   - params *types.RequestParameters
func (_e *MockProjectClient_Expecter) Create(ctx interface{}, body interface{}, params interface{}) *MockProjectClient_Create_Call {
	return &MockProjectClient_Create_Call{Call: _e.mock.On("Create", ctx, body, params)}
}

func (_c *MockProjectClient_Create_Call) Run(run func(ctx context.Context, body types.ProjectRequest, params *types.RequestParameters)) *MockProjectClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ProjectRequest), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockProjectClient_Create_Call) Return(_a0 *types.Response[types.ProjectResponse], _a1 error) *MockProjectClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectClient_Create_Call) RunAndReturn(run func(context.Context, types.ProjectRequest, *types.RequestParameters) (*types.Response[types.ProjectResponse], error)) *MockProjectClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, params
func (_m *MockProjectClient) Delete(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockProjectClient_Expecter) Delete(ctx interface{}, projectID interface{}, params interface{}) *MockProjectClient_Delete_Call {
	return &MockProjectClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, params)}
}

func (_c *MockProjectClient_Delete_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockProjectClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockProjectClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockProjectClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectClient_Delete_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[any], error)) *MockProjectClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, projectID, params
func (_m *MockProjectClient) Get(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[types.ProjectResponse], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Response[types.ProjectResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[types.ProjectResponse], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[types.ProjectResponse]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ProjectResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProjectClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockProjectClient_Expecter) Get(ctx interface{}, projectID interface{}, params interface{}) *MockProjectClient_Get_Call {
	return &MockProjectClient_Get_Call{Call: _e.mock.On("Get", ctx, projectID, params)}
}

func (_c *MockProjectClient_Get_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockProjectClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockProjectClient_Get_Call) Return(_a0 *types.Response[types.ProjectResponse], _a1 error) *MockProjectClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectClient_Get_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[types.ProjectResponse], error)) *MockProjectClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, params
func (_m *MockProjectClient) List(ctx context.Context, params *types.RequestParameters) (*types.Response[types.ProjectList], error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.ProjectList]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.RequestParameters) (*types.Response[types.ProjectList], error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.RequestParameters) *types.Response[types.ProjectList]); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ProjectList])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.RequestParameters) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params *types.RequestParameters
func (_e *MockProjectClient_Expecter) List(ctx interface{}, params interface{}) *MockProjectClient_List_Call {
	return &MockProjectClient_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockProjectClient_List_Call) Run(run func(ctx context.Context, params *types.RequestParameters)) *MockProjectClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockProjectClient_List_Call) Return(_a0 *types.Response[types.ProjectList], _a1 error) *MockProjectClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectClient_List_Call) RunAndReturn(run func(context.Context, *types.RequestParameters) (*types.Response[types.ProjectList], error)) *MockProjectClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, body, params
func (_m *MockProjectClient) Update(ctx context.Context, projectID string, body types.ProjectRequest, params *types.RequestParameters) (*types.Response[types.ProjectResponse], error) {
	ret := _m.Called(ctx, projectID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.ProjectResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.ProjectRequest, *types.RequestParameters) (*types.Response[types.ProjectResponse], error)); ok {
		return rf(ctx, projectID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.ProjectRequest, *types.RequestParameters) *types.Response[types.ProjectResponse]); ok {
		r0 = rf(ctx, projectID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ProjectResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.ProjectRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - body types.ProjectRequest
//   - params *types.RequestParameters
func (_e *MockProjectClient_Expecter) Update(ctx interface{}, projectID interface{}, body interface{}, params interface{}) *MockProjectClient_Update_Call {
	return &MockProjectClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, body, params)}
}

func (_c *MockProjectClient_Update_Call) Run(run func(ctx context.Context, projectID string, body types.ProjectRequest, params *types.RequestParameters)) *MockProjectClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.ProjectRequest), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockProjectClient_Update_Call) Return(_a0 *types.Response[types.ProjectResponse], _a1 error) *MockProjectClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectClient_Update_Call) RunAndReturn(run func(context.Context, string, types.ProjectRequest, *types.RequestParameters) (*types.Response[types.ProjectResponse], error)) *MockProjectClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectClient creates a new instance of MockProjectClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectClient {
	mock := &MockProjectClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
