// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockElasticIPsClient is an autogenerated mock type for the ElasticIPsClient type
type MockElasticIPsClient struct {
	mock.Mock
}

type MockElasticIPsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockElasticIPsClient) EXPECT() *MockElasticIPsClient_Expecter {
	return &MockElasticIPsClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, body, params
func (_m *MockElasticIPsClient) Create(ctx context.Context, projectID string, body types.ElasticIPRequest, params *types.RequestParameters) (*types.Response[types.ElasticIPResponse], error) {
	ret := _m.Called(ctx, projectID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.ElasticIPResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.ElasticIPRequest, *types.RequestParameters) (*types.Response[types.ElasticIPResponse], error)); ok {
		return rf(ctx, projectID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.ElasticIPRequest, *types.RequestParameters) *types.Response[types.ElasticIPResponse]); ok {
		r0 = rf(ctx, projectID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ElasticIPResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.ElasticIPRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElasticIPsClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockElasticIPsClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - body types.ElasticIPRequest
//   - params *types.RequestParameters
func (_e *MockElasticIPsClient_Expecter) Create(ctx interface{}, projectID interface{}, body interface{}, params interface{}) *MockElasticIPsClient_Create_Call {
	return &MockElasticIPsClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, body, params)}
}

func (_c *MockElasticIPsClient_Create_Call) Run(run func(ctx context.Context, projectID string, body types.ElasticIPRequest, params *types.RequestParameters)) *MockElasticIPsClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.ElasticIPRequest), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockElasticIPsClient_Create_Call) Return(_a0 *types.Response[types.ElasticIPResponse], _a1 error) *MockElasticIPsClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElasticIPsClient_Create_Call) RunAndReturn(run func(context.Context, string, types.ElasticIPRequest, *types.RequestParameters) (*types.Response[types.ElasticIPResponse], error)) *MockElasticIPsClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, elasticIPID, params
func (_m *MockElasticIPsClient) Delete(ctx context.Context, projectID string, elasticIPID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, elasticIPID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, elasticIPID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, elasticIPID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, elasticIPID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElasticIPsClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockElasticIPsClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - elasticIPID string
//   - params *types.RequestParameters
func (_e *MockElasticIPsClient_Expecter) Delete(ctx interface{}, projectID interface{}, elasticIPID interface{}, params interface{}) *MockElasticIPsClient_Delete_Call {
	return &MockElasticIPsClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, elasticIPID, params)}
}

func (_c *MockElasticIPsClient_Delete_Call) Run(run func(ctx context.Context, projectID string, elasticIPID string, params *types.RequestParameters)) *MockElasticIPsClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockElasticIPsClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockElasticIPsClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElasticIPsClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockElasticIPsClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, params
func (_m *MockElasticIPsClient) List(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[types.ElasticIPListResponse], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.ElasticIPListResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[types.ElasticIPListResponse], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[types.ElasticIPListResponse]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ElasticIPListResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElasticIPsClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockElasticIPsClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockElasticIPsClient_Expecter) List(ctx interface{}, projectID interface{}, params interface{}) *MockElasticIPsClient_List_Call {
	return &MockElasticIPsClient_List_Call{Call: _e.mock.On("List", ctx, projectID, params)}
}

func (_c *MockElasticIPsClient_List_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockElasticIPsClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockElasticIPsClient_List_Call) Return(_a0 *types.Response[types.ElasticIPListResponse], _a1 error) *MockElasticIPsClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElasticIPsClient_List_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[types.ElasticIPListResponse], error)) *MockElasticIPsClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, elasticIPID, body, params
func (_m *MockElasticIPsClient) Update(ctx context.Context, projectID string, elasticIPID string, body types.ElasticIPRequest, params *types.RequestParameters) (*types.Response[types.ElasticIPResponse], error) {
	ret := _m.Called(ctx, projectID, elasticIPID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.ElasticIPResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.ElasticIPRequest, *types.RequestParameters) (*types.Response[types.ElasticIPResponse], error)); ok {
		return rf(ctx, projectID, elasticIPID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.ElasticIPRequest, *types.RequestParameters) *types.Response[types.ElasticIPResponse]); ok {
		r0 = rf(ctx, projectID, elasticIPID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.ElasticIPResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, types.ElasticIPRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, elasticIPID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElasticIPsClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockElasticIPsClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - elasticIPID string
//   - body types.ElasticIPRequest
//   - params *types.RequestParameters
func (_e *MockElasticIPsClient_Expecter) Update(ctx interface{}, projectID interface{}, elasticIPID interface{}, body interface{}, params interface{}) *MockElasticIPsClient_Update_Call {
	return &MockElasticIPsClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, elasticIPID, body, params)}
}

func (_c *MockElasticIPsClient_Update_Call) Run(run func(ctx context.Context, projectID string, elasticIPID string, body types.ElasticIPRequest, params *types.RequestParameters)) *MockElasticIPsClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(types.ElasticIPRequest), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockElasticIPsClient_Update_Call) Return(_a0 *types.Response[types.ElasticIPResponse], _a1 error) *MockElasticIPsClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElasticIPsClient_Update_Call) RunAndReturn(run func(context.Context, string, string, types.ElasticIPRequest, *types.RequestParameters) (*types.Response[types.ElasticIPResponse], error)) *MockElasticIPsClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockElasticIPsClient creates a new instance of MockElasticIPsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockElasticIPsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockElasticIPsClient {
	mock := &MockElasticIPsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
