// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	aruba "github.com/Arubacloud/sdk-go/pkg/aruba"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockMultitenant is an autogenerated mock type for the Multitenant type
type MockMultitenant struct {
	mock.Mock
}

type MockMultitenant_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMultitenant) EXPECT() *MockMultitenant_Expecter {
	return &MockMultitenant_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: tenant, client
func (_m *MockMultitenant) Add(tenant string, client aruba.Client) {
	_m.Called(tenant, client)
}

// MockMultitenant_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMultitenant_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - tenant string
//   - client aruba.Client
func (_e *MockMultitenant_Expecter) Add(tenant interface{}, client interface{}) *MockMultitenant_Add_Call {
	return &MockMultitenant_Add_Call{Call: _e.mock.On("Add", tenant, client)}
}

func (_c *MockMultitenant_Add_Call) Run(run func(tenant string, client aruba.Client)) *MockMultitenant_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(aruba.Client))
	})
	return _c
}

func (_c *MockMultitenant_Add_Call) Return() *MockMultitenant_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMultitenant_Add_Call) RunAndReturn(run func(string, aruba.Client)) *MockMultitenant_Add_Call {
	_c.Run(run)
	return _c
}

// CleanUp provides a mock function with given fields: from
func (_m *MockMultitenant) CleanUp(from time.Duration) {
	_m.Called(from)
}

// MockMultitenant_CleanUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanUp'
type MockMultitenant_CleanUp_Call struct {
	*mock.Call
}

// CleanUp is a helper method to define mock.On call
//   - from time.Duration
func (_e *MockMultitenant_Expecter) CleanUp(from interface{}) *MockMultitenant_CleanUp_Call {
	return &MockMultitenant_CleanUp_Call{Call: _e.mock.On("CleanUp", from)}
}

func (_c *MockMultitenant_CleanUp_Call) Run(run func(from time.Duration)) *MockMultitenant_CleanUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockMultitenant_CleanUp_Call) Return() *MockMultitenant_CleanUp_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMultitenant_CleanUp_Call) RunAndReturn(run func(time.Duration)) *MockMultitenant_CleanUp_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: tenant
func (_m *MockMultitenant) Get(tenant string) (aruba.Client, bool) {
	ret := _m.Called(tenant)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 aruba.Client
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (aruba.Client, bool)); ok {
		return rf(tenant)
	}
	if rf, ok := ret.Get(0).(func(string) aruba.Client); ok {
		r0 = rf(tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(tenant)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockMultitenant_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMultitenant_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tenant string
func (_e *MockMultitenant_Expecter) Get(tenant interface{}) *MockMultitenant_Get_Call {
	return &MockMultitenant_Get_Call{Call: _e.mock.On("Get", tenant)}
}

func (_c *MockMultitenant_Get_Call) Run(run func(tenant string)) *MockMultitenant_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMultitenant_Get_Call) Return(_a0 aruba.Client, _a1 bool) *MockMultitenant_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMultitenant_Get_Call) RunAndReturn(run func(string) (aruba.Client, bool)) *MockMultitenant_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrNil provides a mock function with given fields: tenant
func (_m *MockMultitenant) GetOrNil(tenant string) aruba.Client {
	ret := _m.Called(tenant)

	if len(ret) == 0 {
		panic("no return value specified for GetOrNil")
	}

	var r0 aruba.Client
	if rf, ok := ret.Get(0).(func(string) aruba.Client); ok {
		r0 = rf(tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.Client)
		}
	}

	return r0
}

// MockMultitenant_GetOrNil_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrNil'
type MockMultitenant_GetOrNil_Call struct {
	*mock.Call
}

// GetOrNil is a helper method to define mock.On call
//   - tenant string
func (_e *MockMultitenant_Expecter) GetOrNil(tenant interface{}) *MockMultitenant_GetOrNil_Call {
	return &MockMultitenant_GetOrNil_Call{Call: _e.mock.On("GetOrNil", tenant)}
}

func (_c *MockMultitenant_GetOrNil_Call) Run(run func(tenant string)) *MockMultitenant_GetOrNil_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMultitenant_GetOrNil_Call) Return(_a0 aruba.Client) *MockMultitenant_GetOrNil_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMultitenant_GetOrNil_Call) RunAndReturn(run func(string) aruba.Client) *MockMultitenant_GetOrNil_Call {
	_c.Call.Return(run)
	return _c
}

// MustGet provides a mock function with given fields: tenant
func (_m *MockMultitenant) MustGet(tenant string) aruba.Client {
	ret := _m.Called(tenant)

	if len(ret) == 0 {
		panic("no return value specified for MustGet")
	}

	var r0 aruba.Client
	if rf, ok := ret.Get(0).(func(string) aruba.Client); ok {
		r0 = rf(tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aruba.Client)
		}
	}

	return r0
}

// MockMultitenant_MustGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustGet'
type MockMultitenant_MustGet_Call struct {
	*mock.Call
}

// MustGet is a helper method to define mock.On call
//   - tenant string
func (_e *MockMultitenant_Expecter) MustGet(tenant interface{}) *MockMultitenant_MustGet_Call {
	return &MockMultitenant_MustGet_Call{Call: _e.mock.On("MustGet", tenant)}
}

func (_c *MockMultitenant_MustGet_Call) Run(run func(tenant string)) *MockMultitenant_MustGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMultitenant_MustGet_Call) Return(_a0 aruba.Client) *MockMultitenant_MustGet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMultitenant_MustGet_Call) RunAndReturn(run func(string) aruba.Client) *MockMultitenant_MustGet_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function with given fields: tenant
func (_m *MockMultitenant) New(tenant string) error {
	ret := _m.Called(tenant)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tenant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMultitenant_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockMultitenant_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - tenant string
func (_e *MockMultitenant_Expecter) New(tenant interface{}) *MockMultitenant_New_Call {
	return &MockMultitenant_New_Call{Call: _e.mock.On("New", tenant)}
}

func (_c *MockMultitenant_New_Call) Run(run func(tenant string)) *MockMultitenant_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMultitenant_New_Call) Return(_a0 error) *MockMultitenant_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMultitenant_New_Call) RunAndReturn(run func(string) error) *MockMultitenant_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewFromOptions provides a mock function with given fields: tenant, options
func (_m *MockMultitenant) NewFromOptions(tenant string, options *aruba.Options) error {
	ret := _m.Called(tenant, options)

	if len(ret) == 0 {
		panic("no return value specified for NewFromOptions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *aruba.Options) error); ok {
		r0 = rf(tenant, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMultitenant_NewFromOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewFromOptions'
type MockMultitenant_NewFromOptions_Call struct {
	*mock.Call
}

// NewFromOptions is a helper method to define mock.On call
//   - tenant string
//   - options *aruba.Options
func (_e *MockMultitenant_Expecter) NewFromOptions(tenant interface{}, options interface{}) *MockMultitenant_NewFromOptions_Call {
	return &MockMultitenant_NewFromOptions_Call{Call: _e.mock.On("NewFromOptions", tenant, options)}
}

func (_c *MockMultitenant_NewFromOptions_Call) Run(run func(tenant string, options *aruba.Options)) *MockMultitenant_NewFromOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*aruba.Options))
	})
	return _c
}

func (_c *MockMultitenant_NewFromOptions_Call) Return(_a0 error) *MockMultitenant_NewFromOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMultitenant_NewFromOptions_Call) RunAndReturn(run func(string, *aruba.Options) error) *MockMultitenant_NewFromOptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMultitenant creates a new instance of MockMultitenant. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMultitenant(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMultitenant {
	mock := &MockMultitenant{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
