// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockVolumesClient is an autogenerated mock type for the VolumesClient type
type MockVolumesClient struct {
	mock.Mock
}

type MockVolumesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumesClient) EXPECT() *MockVolumesClient_Expecter {
	return &MockVolumesClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, body, params
func (_m *MockVolumesClient) Create(ctx context.Context, projectID string, body types.BlockStorageRequest, params *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error) {
	ret := _m.Called(ctx, projectID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.BlockStorageResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.BlockStorageRequest, *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error)); ok {
		return rf(ctx, projectID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.BlockStorageRequest, *types.RequestParameters) *types.Response[types.BlockStorageResponse]); ok {
		r0 = rf(ctx, projectID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.BlockStorageResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.BlockStorageRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumesClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVolumesClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - body types.BlockStorageRequest
//   - params *types.RequestParameters
func (_e *MockVolumesClient_Expecter) Create(ctx interface{}, projectID interface{}, body interface{}, params interface{}) *MockVolumesClient_Create_Call {
	return &MockVolumesClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, body, params)}
}

func (_c *MockVolumesClient_Create_Call) Run(run func(ctx context.Context, projectID string, body types.BlockStorageRequest, params *types.RequestParameters)) *MockVolumesClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.BlockStorageRequest), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVolumesClient_Create_Call) Return(_a0 *types.Response[types.BlockStorageResponse], _a1 error) *MockVolumesClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumesClient_Create_Call) RunAndReturn(run func(context.Context, string, types.BlockStorageRequest, *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error)) *MockVolumesClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, volumeID, params
func (_m *MockVolumesClient) Delete(ctx context.Context, projectID string, volumeID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, volumeID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, volumeID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, volumeID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, volumeID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumesClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVolumesClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - volumeID string
//   - params *types.RequestParameters
func (_e *MockVolumesClient_Expecter) Delete(ctx interface{}, projectID interface{}, volumeID interface{}, params interface{}) *MockVolumesClient_Delete_Call {
	return &MockVolumesClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, volumeID, params)}
}

func (_c *MockVolumesClient_Delete_Call) Run(run func(ctx context.Context, projectID string, volumeID string, params *types.RequestParameters)) *MockVolumesClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVolumesClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockVolumesClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumesClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockVolumesClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, projectID, volumeID, params
func (_m *MockVolumesClient) Get(ctx context.Context, projectID string, volumeID string, params *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error) {
	ret := _m.Called(ctx, projectID, volumeID, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Response[types.BlockStorageResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error)); ok {
		return rf(ctx, projectID, volumeID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[types.BlockStorageResponse]); ok {
		r0 = rf(ctx, projectID, volumeID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.BlockStorageResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, volumeID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumesClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVolumesClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - volumeID string
//   - params *types.RequestParameters
func (_e *MockVolumesClient_Expecter) Get(ctx interface{}, projectID interface{}, volumeID interface{}, params interface{}) *MockVolumesClient_Get_Call {
	return &MockVolumesClient_Get_Call{Call: _e.mock.On("Get", ctx, projectID, volumeID, params)}
}

func (_c *MockVolumesClient_Get_Call) Run(run func(ctx context.Context, projectID string, volumeID string, params *types.RequestParameters)) *MockVolumesClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVolumesClient_Get_Call) Return(_a0 *types.Response[types.BlockStorageResponse], _a1 error) *MockVolumesClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumesClient_Get_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error)) *MockVolumesClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, params
func (_m *MockVolumesClient) List(ctx context.Context, projectID string, params *types.RequestParameters) (*types.Response[types.BlockStorageList], error) {
	ret := _m.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.BlockStorageList]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) (*types.Response[types.BlockStorageList], error)); ok {
		return rf(ctx, projectID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.RequestParameters) *types.Response[types.BlockStorageList]); ok {
		r0 = rf(ctx, projectID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.BlockStorageList])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumesClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVolumesClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params *types.RequestParameters
func (_e *MockVolumesClient_Expecter) List(ctx interface{}, projectID interface{}, params interface{}) *MockVolumesClient_List_Call {
	return &MockVolumesClient_List_Call{Call: _e.mock.On("List", ctx, projectID, params)}
}

func (_c *MockVolumesClient_List_Call) Run(run func(ctx context.Context, projectID string, params *types.RequestParameters)) *MockVolumesClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVolumesClient_List_Call) Return(_a0 *types.Response[types.BlockStorageList], _a1 error) *MockVolumesClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumesClient_List_Call) RunAndReturn(run func(context.Context, string, *types.RequestParameters) (*types.Response[types.BlockStorageList], error)) *MockVolumesClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, volumeID, body, params
func (_m *MockVolumesClient) Update(ctx context.Context, projectID string, volumeID string, body types.BlockStorageRequest, params *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error) {
	ret := _m.Called(ctx, projectID, volumeID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.BlockStorageResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.BlockStorageRequest, *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error)); ok {
		return rf(ctx, projectID, volumeID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.BlockStorageRequest, *types.RequestParameters) *types.Response[types.BlockStorageResponse]); ok {
		r0 = rf(ctx, projectID, volumeID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.BlockStorageResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, types.BlockStorageRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, volumeID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumesClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVolumesClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - volumeID string
//   - body types.BlockStorageRequest
//   - params *types.RequestParameters
func (_e *MockVolumesClient_Expecter) Update(ctx interface{}, projectID interface{}, volumeID interface{}, body interface{}, params interface{}) *MockVolumesClient_Update_Call {
	return &MockVolumesClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, volumeID, body, params)}
}

func (_c *MockVolumesClient_Update_Call) Run(run func(ctx context.Context, projectID string, volumeID string, body types.BlockStorageRequest, params *types.RequestParameters)) *MockVolumesClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(types.BlockStorageRequest), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockVolumesClient_Update_Call) Return(_a0 *types.Response[types.BlockStorageResponse], _a1 error) *MockVolumesClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumesClient_Update_Call) RunAndReturn(run func(context.Context, string, string, types.BlockStorageRequest, *types.RequestParameters) (*types.Response[types.BlockStorageResponse], error)) *MockVolumesClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumesClient creates a new instance of MockVolumesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumesClient {
	mock := &MockVolumesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
