// Code generated by mockery. DO NOT EDIT.

package arubamocks

import (
	context "context"

	types "github.com/Arubacloud/sdk-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockSubnetsClient is an autogenerated mock type for the SubnetsClient type
type MockSubnetsClient struct {
	mock.Mock
}

type MockSubnetsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubnetsClient) EXPECT() *MockSubnetsClient_Expecter {
	return &MockSubnetsClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, vpcID, body, params
func (_m *MockSubnetsClient) Create(ctx context.Context, projectID string, vpcID string, body types.SubnetRequest, params *types.RequestParameters) (*types.Response[types.SubnetResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.Response[types.SubnetResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.SubnetRequest, *types.RequestParameters) (*types.Response[types.SubnetResponse], error)); ok {
		return rf(ctx, projectID, vpcID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, types.SubnetRequest, *types.RequestParameters) *types.Response[types.SubnetResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SubnetResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, types.SubnetRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubnetsClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubnetsClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - body types.SubnetRequest
//   - params *types.RequestParameters
func (_e *MockSubnetsClient_Expecter) Create(ctx interface{}, projectID interface{}, vpcID interface{}, body interface{}, params interface{}) *MockSubnetsClient_Create_Call {
	return &MockSubnetsClient_Create_Call{Call: _e.mock.On("Create", ctx, projectID, vpcID, body, params)}
}

func (_c *MockSubnetsClient_Create_Call) Run(run func(ctx context.Context, projectID string, vpcID string, body types.SubnetRequest, params *types.RequestParameters)) *MockSubnetsClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(types.SubnetRequest), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSubnetsClient_Create_Call) Return(_a0 *types.Response[types.SubnetResponse], _a1 error) *MockSubnetsClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubnetsClient_Create_Call) RunAndReturn(run func(context.Context, string, string, types.SubnetRequest, *types.RequestParameters) (*types.Response[types.SubnetResponse], error)) *MockSubnetsClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, vpcID, subnetID, params
func (_m *MockSubnetsClient) Delete(ctx context.Context, projectID string, vpcID string, subnetID string, params *types.RequestParameters) (*types.Response[any], error) {
	ret := _m.Called(ctx, projectID, vpcID, subnetID, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *types.Response[any]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[any], error)); ok {
		return rf(ctx, projectID, vpcID, subnetID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) *types.Response[any]); ok {
		r0 = rf(ctx, projectID, vpcID, subnetID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[any])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, subnetID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubnetsClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubnetsClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - subnetID string
//   - params *types.RequestParameters
func (_e *MockSubnetsClient_Expecter) Delete(ctx interface{}, projectID interface{}, vpcID interface{}, subnetID interface{}, params interface{}) *MockSubnetsClient_Delete_Call {
	return &MockSubnetsClient_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, vpcID, subnetID, params)}
}

func (_c *MockSubnetsClient_Delete_Call) Run(run func(ctx context.Context, projectID string, vpcID string, subnetID string, params *types.RequestParameters)) *MockSubnetsClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSubnetsClient_Delete_Call) Return(_a0 *types.Response[any], _a1 error) *MockSubnetsClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubnetsClient_Delete_Call) RunAndReturn(run func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[any], error)) *MockSubnetsClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, projectID, vpcID, subnetID, params
func (_m *MockSubnetsClient) Get(ctx context.Context, projectID string, vpcID string, subnetID string, params *types.RequestParameters) (*types.Response[types.SubnetResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, subnetID, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Response[types.SubnetResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[types.SubnetResponse], error)); ok {
		return rf(ctx, projectID, vpcID, subnetID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *types.RequestParameters) *types.Response[types.SubnetResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, subnetID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SubnetResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, subnetID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubnetsClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSubnetsClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - subnetID string
//   - params *types.RequestParameters
func (_e *MockSubnetsClient_Expecter) Get(ctx interface{}, projectID interface{}, vpcID interface{}, subnetID interface{}, params interface{}) *MockSubnetsClient_Get_Call {
	return &MockSubnetsClient_Get_Call{Call: _e.mock.On("Get", ctx, projectID, vpcID, subnetID, params)}
}

func (_c *MockSubnetsClient_Get_Call) Run(run func(ctx context.Context, projectID string, vpcID string, subnetID string, params *types.RequestParameters)) *MockSubnetsClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSubnetsClient_Get_Call) Return(_a0 *types.Response[types.SubnetResponse], _a1 error) *MockSubnetsClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubnetsClient_Get_Call) RunAndReturn(run func(context.Context, string, string, string, *types.RequestParameters) (*types.Response[types.SubnetResponse], error)) *MockSubnetsClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID, vpcID, params
func (_m *MockSubnetsClient) List(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters) (*types.Response[types.SubnetList], error) {
	ret := _m.Called(ctx, projectID, vpcID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *types.Response[types.SubnetList]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.SubnetList], error)); ok {
		return rf(ctx, projectID, vpcID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.RequestParameters) *types.Response[types.SubnetList]); ok {
		r0 = rf(ctx, projectID, vpcID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SubnetList])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubnetsClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubnetsClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - params *types.RequestParameters
func (_e *MockSubnetsClient_Expecter) List(ctx interface{}, projectID interface{}, vpcID interface{}, params interface{}) *MockSubnetsClient_List_Call {
	return &MockSubnetsClient_List_Call{Call: _e.mock.On("List", ctx, projectID, vpcID, params)}
}

func (_c *MockSubnetsClient_List_Call) Run(run func(ctx context.Context, projectID string, vpcID string, params *types.RequestParameters)) *MockSubnetsClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSubnetsClient_List_Call) Return(_a0 *types.Response[types.SubnetList], _a1 error) *MockSubnetsClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubnetsClient_List_Call) RunAndReturn(run func(context.Context, string, string, *types.RequestParameters) (*types.Response[types.SubnetList], error)) *MockSubnetsClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, projectID, vpcID, subnetID, body, params
func (_m *MockSubnetsClient) Update(ctx context.Context, projectID string, vpcID string, subnetID string, body types.SubnetRequest, params *types.RequestParameters) (*types.Response[types.SubnetResponse], error) {
	ret := _m.Called(ctx, projectID, vpcID, subnetID, body, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.Response[types.SubnetResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, types.SubnetRequest, *types.RequestParameters) (*types.Response[types.SubnetResponse], error)); ok {
		return rf(ctx, projectID, vpcID, subnetID, body, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, types.SubnetRequest, *types.RequestParameters) *types.Response[types.SubnetResponse]); ok {
		r0 = rf(ctx, projectID, vpcID, subnetID, body, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response[types.SubnetResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, types.SubnetRequest, *types.RequestParameters) error); ok {
		r1 = rf(ctx, projectID, vpcID, subnetID, body, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubnetsClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubnetsClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - vpcID string
//   - subnetID string
//   - body types.SubnetRequest
//   - params *types.RequestParameters
func (_e *MockSubnetsClient_Expecter) Update(ctx interface{}, projectID interface{}, vpcID interface{}, subnetID interface{}, body interface{}, params interface{}) *MockSubnetsClient_Update_Call {
	return &MockSubnetsClient_Update_Call{Call: _e.mock.On("Update", ctx, projectID, vpcID, subnetID, body, params)}
}

func (_c *MockSubnetsClient_Update_Call) Run(run func(ctx context.Context, projectID string, vpcID string, subnetID string, body types.SubnetRequest, params *types.RequestParameters)) *MockSubnetsClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(types.SubnetRequest), args[5].(*types.RequestParameters))
	})
	return _c
}

func (_c *MockSubnetsClient_Update_Call) Return(_a0 *types.Response[types.SubnetResponse], _a1 error) *MockSubnetsClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubnetsClient_Update_Call) RunAndReturn(run func(context.Context, string, string, string, types.SubnetRequest, *types.RequestParameters) (*types.Response[types.SubnetResponse], error)) *MockSubnetsClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubnetsClient creates a new instance of MockSubnetsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubnetsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubnetsClient {
	mock := &MockSubnetsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
